### ISSUE TITLE
orc shaman racial display bug

### ISSUE THREAD

**Issue by third0ne** [ccshiro/cc-buglist#629] opened 2015-06-06 13:24 UTC
'Blood fury' in spellbook display base value on lvl 1, after lvling it still display same. After using it give proper value of Attack power. 
Another one is racial with axe skill, dont know if it work as it rather hard 2 check if i got 355 or 350. but it does not display in skills chart +5 weapon skill i got from racial.

**Comment by ccshiro** [comment] 2015-06-06 14:17
Duplicate of #175.

**Closed as completed by ccshiro** 2015-06-06 14:17 UTC
Labels: duplicate
