### ISSUE TITLE
[NPC][Shadow Labs] NPC shooting while sheeped

### ISSUE THREAD

**Issue by ghost** [ccshiro/cc-buglist#1584] opened 2015-09-02 00:42 UTC
As can be seen in the SS, lightly, the arcane missiles from the sheep are hitting the priest, also, it can be seen that the enermy cast bar above my target is fading (i guess i was too slow to take the SS as soon as i freaked out)
inbefore any claims. mob was SHEEPED before the arcane missile cast.

NOTE: while this happened i was suffering massive lags, so it might be caused by it
![captura de pantalla 2015-09-02 a las 1 54 27](https://cloud.githubusercontent.com/assets/13721369/9620567/c3ec502e-511b-11e5-8c64-bb13f601e491.png)

**Comment by KimmoKM** [comment] 2015-09-02 03:56
I've seen the same issue on other private servers without any lag being involved.

**Comment by ccshiro** [comment] 2015-09-03 13:56
Duplicate of #1396.

**Closed as completed by ccshiro** 2015-09-03 13:56 UTC
Labels: duplicate
