### ISSUE TITLE
Blood Furnace: trash mobs before final boss started evading during kiting

### ISSUE THREAD

**Issue by brndd** [ccshiro/cc-buglist#699] opened 2015-06-07 13:02 UTC
(posting some bugs for another person who doesn't have a github account)

We pulled the mobs [editorial note: Felguard Annihilators before the final boss] and kited them up. while running up the ramp the mobs started evading as it can be seen in the pictures

after the tank and the mage (the only people on the mobs threat table) died, the mobs stuck on evade, after some time they just reseted and ignored us completely allowing us to res the group.

Screenshots:
![6](https://cloud.githubusercontent.com/assets/5822375/8024040/69ce66a4-0d2d-11e5-9133-7f9ecb85d8f3.jpg)
![11](https://cloud.githubusercontent.com/assets/5822375/8024041/69cfeb78-0d2d-11e5-8a86-a12f804f906e.jpg)
![4](https://cloud.githubusercontent.com/assets/5822375/8024042/69d62696-0d2d-11e5-9ea8-e47b6c79ffa7.jpg)
![5](https://cloud.githubusercontent.com/assets/5822375/8024043/69d811f4-0d2d-11e5-91ff-d31ac5f8e778.jpg)

**Comment by ccshiro** [comment] 2015-06-24 15:28
Unable to reproduce. Also this report is missing the .movegens --verbose in the screenshots as was described in the paste. Moving to needs testing, so that screenshots with the needed information can be submitted if encountered again.

**Comment by ccshiro** [comment] 2016-02-14 12:11
A lot of movement issues have been fixed since this report, and I haven't heard this issue repeated by groups running BF more recently. I'll assume it's gone and close this.

**Closed as completed by ccshiro** 2016-02-14 12:11 UTC
Labels: cannot reproduce
