### ISSUE TITLE
The Fel and the Furious

### ISSUE THREAD

**Issue by Kplz** [ccshiro/cc-buglist#1256] opened 2015-08-10 14:28 UTC
http://www.wowhead.com/quest=10613/the-fel-and-the-furious Can't move after i leave reaver. Need to  quit game to move again.

**Comment by ConfusedCC** [comment] 2015-08-10 22:04
duplicate of a comment in #142

**Comment by ccshiro** [comment] 2015-08-14 02:31
Duplicate of #142, please post any info you have in there.

**Closed as completed by ccshiro** 2015-08-14 02:31 UTC
Labels: duplicate
