### ISSUE TITLE
Rogue vanish bug

### ISSUE THREAD

**Issue by Stoffetest** [ccshiro/cc-buglist#1122] opened 2015-08-08 11:15 UTC
This needs more investigation, however, 4/5 times I vanish from a melee class they just keep attacking me as if I just ran that direction. I'm aware of the state vanish was in 2.0 and vanish would break due to projectiles being sent your way as you vanished, but now, literally everything is breaking my vanish. And no, I'm not talking about dots.

As stated above, needs more research about what exactly is the problem.

**Comment by Doope** [comment] 2015-08-08 11:28
Welcome to the burning crusade

**Comment by Stoffetest** [comment] 2015-08-08 11:31
If you're going to comment on this section, please be constructive. I'm aware of how Vanish worked.

**Comment by Stoffetest** [comment] 2015-08-08 12:40
Also just noticed if you resist a spell whilst using vanish, you get popped out of stealth. This only happens sometimes, so the causes are unknown. This means, cloak + vanish against say a Shadow Priest doesn't work from time to time. That being said, still no dot damage causing this.

**Comment by ceyscro** [comment] 2015-08-08 16:35
Doope wrote that because this issue was present in TBC retail, there where some treads on forums about that.
The fact is that vanish can "absorb" all ranged spells and you will still be in vanish mode. But vanish can also "absorb" melee stuns, when it happen you pop out from stealth, this is mostly known happening from a blind vanish, that do not happen only with blind but with all melee stuns.

**Comment by Peonstomperx** [comment] 2015-08-08 17:25
Let's nerf rogues some more because I feel like playing warlock after all these nerfs.

Blind breaks vanish:
https://www.youtube.com/watch?v=xF4Rx1sQYQU&t=74 
Vanish should break when the spell batch happens, watch the vanish buff.

Some more spells that should break vanish, however cheap shot and kidney are auto attacked aswell, they need more proof.
https://www.youtube.com/watch?v=TTDbFBbNgyw

https://www.youtube.com/watch?v=xF4Rx1sQYQU&t=68
He seems to be able to get cheap shot off with that small vanish window.
Should it be possible to sap aswell? Does combat happen when the spell starts queing, or after the batch?

**Comment by ceyscro** [comment] 2015-08-08 18:33
What's your question here?

**Comment by Schaka** [comment] 2015-08-08 19:55
Also, other rogues can vanish my cheap shot, I will get out of stealth, but their vanish will not break.
This is not how it is supposed to work. If you vanish an instant spell that isn't a projectile (like blind, cheap shot, etc) you are immune to the spell, but vanish/stealth also breaks.

**Comment by nullfoxh** [comment] 2015-08-08 22:37
Proof for the issue in post number 4 "if you resist a spell whilst using vanish, you get popped out of stealth":

Resisted spells will no longer break "Stealth"/"Vanish".
http://us.battle.net/wow/en/game/patch-notes/2-0-3

**Comment by Peonstomperx** [comment] 2015-08-08 23:08
More proof for what Schaka and I were talking about: https://www.youtube.com/watch?v=fT_aZfg9AP0&t=663

**Comment by justinbeaver** [comment] 2015-08-15 15:54
Deadly Throw breaks vanish
https://youtu.be/D_iQHXtod6Y?t=237

**Comment by Aasamath** [comment] 2015-08-15 16:31
@Peonstomperx  about the vanish blind then sap trick. That specific one is impossible simply because vanishing doesn't remove combat on your target.
you need him to vanish as well or wait for combat to break.
https://www.youtube.com/watch?v=NkIhYTotbdM 11:20 fight (its tlk but that doesn't change this mechanic)

As to if you can vanish blind and cast an opener at the same time i don't know.
https://www.youtube.com/watch?v=xF4Rx1sQYQU 1:10
if you watch in slowmotion the vanish, you can see his action bar changes to stealth one, but sap, and cheap shot seem to be greyed out.

**Comment by Schaka** [comment] 2015-08-15 17:33
@justinbeaver not sure it was deadly throw or just him breaking his own vanish somehow (since cheap shot was greyed out too), as it would sometimes happen to people smashing stealth keybinds too quickly and then using the non-stealth one

@Aasamath in 3.x, blind doesn't put you in combat, so you can blind an opponent out of combat. Vanish drops combat on yourself, so spamming sap on an opponent as he vanishes is almost entirely guaranteed to land sap and break vanish. Woundman got really confused when this didn't work on TBC AT.

Instant spells break vanish all the time when they get avoided by it. Maybe projectiles break it sometimes. The so-called vanish bug was common knowledge on retail. However, I'd be very surprised if you could find a video of an instant spell (no projectile) being swallowed by vanish without it breaking.

**Comment by justinbeaver** [comment] 2015-08-17 01:44
<b>neilyo blind breaks vanish</b>
![druidrogue_vs_rogue_priest wmv_snapshot_02 31_ 2015 08 16_18 25 11](https://cloud.githubusercontent.com/assets/13700367/9296618/e45a53d4-4445-11e5-9355-dd1c4ebb1073.jpg)
![druidrogue_vs_rogue_priest wmv_snapshot_02 31_ 2015 08 16_18 25 47](https://cloud.githubusercontent.com/assets/13700367/9296619/e7adacc0-4445-11e5-857e-513bbc98c11d.jpg)
![druidrogue_vs_rogue_priest wmv_snapshot_02 32_ 2015 08 16_18 25 59](https://cloud.githubusercontent.com/assets/13700367/9296620/e95a72ec-4445-11e5-8c82-7afbf4cae6a4.jpg)
<b>Deadly throw breaks vanish? -487dmg</b>
![druidrogue_vs_rogue_priest wmv_snapshot_06 20_ 2015 08 16_18 27 55](https://cloud.githubusercontent.com/assets/13700367/9296625/229bc678-4446-11e5-8d60-8f9867af7dae.jpg)
![druidrogue_vs_rogue_priest wmv_snapshot_06 21_ 2015 08 16_18 30 13](https://cloud.githubusercontent.com/assets/13700367/9296626/24b30ca0-4446-11e5-9b04-2d871e5b9751.jpg)
<b>gouge breaks stealth</b>
![druidrogue_vs_rogue_priest wmv_snapshot_09 02_ 2015 08 16_18 32 01](https://cloud.githubusercontent.com/assets/13700367/9296647/50862df8-4446-11e5-9dde-17b5ed860875.jpg)
![druidrogue_vs_rogue_priest wmv_snapshot_09 03_ 2015 08 16_18 32 13](https://cloud.githubusercontent.com/assets/13700367/9296649/52693200-4446-11e5-8024-b801965ca878.jpg)
![druidrogue_vs_rogue_priest wmv_snapshot_09 03_ 2015 08 16_18 32 42](https://cloud.githubusercontent.com/assets/13700367/9296650/53f82d92-4446-11e5-8a12-a8df04f3b753.jpg)
looks like only on sk gaming you can find this movie http://www.sk-gaming.com/file/6124-NeilyoSerennia_vs_RoguePriest
click >> DOWNLOAD 'DruidRogue_vs_Rogue_Priest.wmv' 183,399 KB <<

offtopic: scatter breaks stealth jk :D Track Hidden>all
https://cloud.githubusercontent.com/assets/13700367/9296777/11355bf8-4449-11e5-8879-341a7c8cf8d5.jpg

**Comment by Schaka** [comment] 2015-08-17 07:38
@justinbeaver thank you! I forgot that there is actually another outcome where blind will break vanish and stay on the target. I always attributed this to casting blind after vanish or vanish after blind, whichever way around. Played too much on privates and forgot this existed.

**Comment by ccshiro** [comment] 2015-08-22 16:04
What is the actual bug report here? Could someone summarize the issue that's reported, or could OP edit his post?

**Comment by nullfoxh** [comment] 2015-08-22 17:11
@ccshiro 
In post 1 OP said melee hits were breaking vanish too often. No proof yet.
In post 4 OP said resisted spells were also breaking vanish. I posted patch notes as proof this should not happen.

Rest seemed to be off-topic discussion, on blind/stuns breaking vanish which seems to be working as intended.

**Comment by justinbeaver** [comment] 2015-08-23 15:17
@nullv0id What is interested to me is in Neilyo 11 stealth breaks when spell is resisted.

Patch 2.0.3 "Resisted spells will no longer break "Stealth"/"Vanish"."
But it happens far from 2.0.3 in season 3, 2.3.0+.
![neilyo11 wmv_snapshot_13 56_ 2015 08 23_08 03 00](https://cloud.githubusercontent.com/assets/13700367/9428793/0b321e14-496f-11e5-9f9f-a6b82bf1347f.jpg)
![neilyo11 wmv_snapshot_13 56_ 2015 08 23_08 03 34](https://cloud.githubusercontent.com/assets/13700367/9428794/0eb15834-496f-11e5-830d-97b31b6de1fa.jpg)
![neilyo11 wmv_snapshot_13 57_ 2015 08 23_08 03 44](https://cloud.githubusercontent.com/assets/13700367/9428795/10ddecf8-496f-11e5-8b4c-96d0fdc315bb.jpg)

https://www.youtube.com/watch?v=t8iiLNszJpU&feature=youtu.be&t=833

**Comment by nullfoxh** [comment] 2015-08-23 19:31
So their bug fix wasn't 100%? Intent was to fix it and it seems there seems to be less complaining about it as well. Resists breaking stealth hardly makes sense anyway :)

**Comment by justinbeaver** [comment] 2015-08-29 15:30
Vanish breaks by hemorrhage
<b>Cheapshot3.wmv</b>
<b>1:25</b>
![cheapshot3 wmv_snapshot_01 27_ 2015 08 29_17 15 10](https://cloud.githubusercontent.com/assets/13700367/9562676/dadd4dd0-4e7b-11e5-827f-96f983d64f38.jpg)
![cheapshot3 wmv_snapshot_01 27_ 2015 08 29_17 15 21](https://cloud.githubusercontent.com/assets/13700367/9562677/dd877baa-4e7b-11e5-8a8f-6c5036f93952.jpg)
![cheapshot3 wmv_snapshot_01 28_ 2015 08 29_17 15 27](https://cloud.githubusercontent.com/assets/13700367/9562679/dec02d32-4e7b-11e5-9534-e92cbefada87.jpg)
WCM link: <I>http://www.warcraftmovies.com/movieview.php?id=69243</i>
Gamefront download: <i>http://www.gamefront.com/files/Cheapshot3wmv/;9921794;/fileinfo.html</i>

**Comment by nullfoxh** [comment] 2015-08-29 17:29
@justinbeaver
Pretty sure we've had this conversation a few times now.
Yes, you can break vanish and nobody is trying to dispute it.

**Comment by justinbeaver** [comment] 2015-08-29 18:32
@nullv0id 
Report is still open, and one more proper proof won't be redundant.

**Comment by nullfoxh** [comment] 2015-08-29 18:58
@justinbeaver I'm sorry, I don't understand, what is it you are proving? I mean nobody has said hemo shouldn't break vanish, from what I've understood anyway. Quite the opposite actually, as the mechanic of breaking vanish is acknowledged by the devs and has been implemented on the server. All I'm saying is, it seemed redundant as nobody was disagreeing with you :)

**Comment by robinsch** [comment] 2015-08-29 19:20
There is a delay on the stealth apply, if you melee attack in this window stealth and vanish will break.

About other stuff:
Blind can break Vanish and stay on target, also Vanish can absorb blind and will break vanish.
all instant spells should break vanish (this excludes: Shadowfury?)
all delayed spells should not break vanish (this excludes: Charge / Intercept / Scatter Shot)

**Comment by Aasamath** [comment] 2015-08-29 19:23
The issue reported states that in pvp melee class seem to break vanish too often.
This is due to vanish leaving you targeted for a short period of time once the "evade" mechanic has run out.
I tested and recorded some vanish on the server and that time frame was extremly short most of the time. I don't think there is an issue there (or didn't do enough vanish).
Vanishing in melee range was extremly dangerous vs dual wielding and "spamming"classes like rogue, enh shaman and hunter (with pet). Because of the high number of hit per second, there is a strong chance one of these hits will hit you just before you disappear.
The best example of this is the snake trap, chances to vanish successfully with snakes on you are close to 0.

@justinbeaver scenarios of abilities "canceling" vanish are welcome here though #1545 
the two things we could find out with such screens are wihch abilities cancel vanish, and which don't. And by cancel i mean that they were "avoided" but still made the rogue reappear. For example the "gouge breaks blind" in this topic isn't a cancel since it did damage, it's a break. The hemorraghe one might be though (haven't been able to check the clip yet).
Other thing kinda related is how fly time spells work with vanish (this is explained at the bottom of the topic i linked).

**Comment by justinbeaver** [comment] 2015-08-29 20:08
@Aasamath <i>"Vanishing in melee range was extremly dangerous ... you are close to 0."</i>

That's is true, you don't have any chances to vanish when warrior and rogue cleaving you in 3s, same when pet and hunter hitting you, but I had a conversation with shiro and he said that pet wont break vanish so often like it was in retail.

---

@robinsch <i>"all delayed spells should not break vanish"</i>

do you mean abilities with travel time? if you do, then it is exactly the opposite, every hunter shot has a travel time, and they break vanish with ease.

For example:
<i>rogue is using vanish and hunter is shooting at the same time
rogue is gaining "immunity from hits", hunter's shot is still in-flight
rogue is stealthed, hunter's shot hit him in stealth and break vanish</i>

That's why it's so easy to break vanish unintentionally for hunter with pet and shots.
On every private server vanish is working like "oh shit button" which is not blizzlike at all:D

---

Random topics about vanish break if someone is interested:
<I>http://www.arenajunkies.com/topic/35712-how-to-vanish/
http://www.mmo-champion.com/threads/972292-How-do-hunters-see-through-vanish
often it's a ranged attack that was fired at approximately same time you vanished and wasn't immuned by the vanish
http://www.arenajunkies.com/topic/83429-hunters-breaking-vanish-unintentionally/
"0.00 rogue vanish
1.00 hunters shoot.
1.50 hunters sees the rogue using vanish
3.00 vanish immunity fades of the rogue
3.10 arrow hits the rogue. BAM rogue wasted a vanish."
http://www.mmo-champion.com/threads/1083640-Hunters-breaking-my-stealth</i>

Pretty much what I've explained above, but this one from 2012

---

UPDATE:
@Aasamath 
I think you can't make such a list because you can find movie where rogue is using vanish and blind break his vanish and last for 10 sec, and video where rogue using vanish and blind just canceling vanish but don't appied blind debuff.
But maybe it's because blind and vanish was used in same time, and when blind was used after vanish.
UPDATE 2:
But could be different for spells with travel time and ranged (physical) attacks with travel time.
Blind is ranged (physical) attack tho

**Comment by Aasamath** [comment] 2015-08-29 20:23
I don't remenber seeing blind and vanish both being cancel but if it can then yeah, the "same time" scenario is something i've wondering about and might look like that.
Could also be due to blind still being a poison attack up to 2.3.0.

**Comment by Peonstomperx** [comment] 2015-08-31 13:28
@justinbeaver @nullv0id regarding resist breaking stealth in that video, it could be that cloak and regular spell resists act differently, since cloak = miss spells(which displays as resist) and resistance = resist, maybe normal resists should break stealth but misses shouldn't

**Comment by DarkenRal** [comment] 2016-01-23 04:06
> Deadly Throw breaks vanish
> https://youtu.be/D_iQHXtod6Y?t=237
> 
> not sure it was deadly throw or just him breaking his own vanish somehow (since cheap shot was greyed out too), as it would sometimes happen to people smashing stealth keybinds too quickly and then using the non-stealth one

actually, if someone still intrested, DT doesn't breakes Vanish just like all other spells with travel time. But the rogue's PvP gloves bonus does, since it gives you instant interrupt.

**Comment by Ickler** [comment] 2016-02-13 23:45
I would like to reinforce the OP here. 

What applies to every single movie with proof shown here is that Vanish breaks from instant abilities. 
Aside from Blind (instant ranged ability without travel time), I have not seen once that Vanish breaks from anything else and you ALSO receive the effect. 

Movie posted by Justin, which I downloaded.. Shows this clearly too, enemy rogue vanishes and this vanish is broken by either a rupture or a Hemo, I can't really tell.. Anyway enemy rogue runs away with no hemo or rupture debuf. 

What we see on Corecraft, and that I feel is completely wrong is that melee abilities and attacks (it looks like) can land in what I think Shiro calls the "vanish grace period", where you still see the rogue. It will break the rogues stealth, but also apply the effect / damage of whatever broke his stealth/vanish. 

I can list some 15+ movies if Devs are interested in watching, or I can dig up many more where what happens on Corecraft to 90% of vanishes in melee range with several combatants, never happens. Not even once. 

The predicament here is, we have something happening on Corecraft that I argue didn't happen on retail. How does one prove that? Only way I see it is by bulk evidence and comparing to actual PvP on Corecraft. 
In my eyes unless you find specific proof that melee attacks and abilities should be able to land in "the grace period", I would say this should be changed. And burden of proof should be on finding this occurrence on retail, not showing countless videos where it doesn't happen. Lack of proof is also proof, however in this case one shouldn't even need to provide the lack of occurrences if someone can't find a specific case where this happens. 

So what happens on Corecraft because of this is what OP outlines... 

Retail: Only way for a melee to cancel out a vanish was to land a well timed ability (or very very lucky) that landed the exact moment of the vanish.. In which the effect would be rogue loses his vanish / stealth, but no damage or debuff is applied from the attack that broke it since this was "Vanished".

Corecraft: Melee hits and melee abilities can all land within a very easy to hit "grace period" which makes vanish next to useless in many situations. Furthermore you don't just lose the stealth and the vanish, but you also get the effect/damage of whatever was used... So a rogue can Kidney shot another rogues vanish, and the rogue who vanished will lose his vanish and be stunned from Kidney. 

I want to see an occurrence from TBC where this happens. Patch 3.0.0 and beyond is not acceptable. And if there aren't any to be found, I will provide all the rogue PvP movies I know of and Devs can watch how this doesn't happen.

**Comment by ccnim** [comment] 2016-03-02 20:11
Some useful finds
https://youtu.be/fT_aZfg9AP0?t=400 Dot damage unstealths you immediately
https://youtu.be/fT_aZfg9AP0?t=891 Melee abilities being able to leave debuffs?
https://youtu.be/fT_aZfg9AP0?t=787 Again instant removal from stealth by dot
http://www.mmo-champion.com/threads/613086-Is-Vanish-still-gonna-be-bugged?p=5698216&viewfull=1#post5698216

**Comment by DarkenRal** [comment] 2016-03-02 22:12
@ccnim ofc dot damage breaks vanish instantly, any damage breaks vanish instantly :O 

> https://youtu.be/fT_aZfg9AP0?t=891 Melee abilities being able to leave debuffs?

ofc, if it breaks vanish (it was hemo hit into vanish; you can also evade melee atacks, same way you evade blinds and ofc vanish will be broken but no damge and no debuff).

**Comment by Ickler** [comment] 2016-03-03 01:21
Well I know that if you have high stealth detection, heigthened senses + engi goggles if a rogue vanishes in front of you, you can still see him. Especially if he misses stealth on cloak. This might be what happens in Neilyo 14. Can't really tell if the enemy rogue is wearing goggles, seems he doesn't show his head. 

However that would be my critique to that clip. Same thing happens if you vanish in front of someone with goggles + paranoia or Perception, or God forbid all 3... They will never lose sight of you, and thus can just use abilities on you at will. 

Neilyo in this clip plays with a resto druid, and has access to pve gear. Most likely he doesn't wear stealth on cloak and runs with 12agi instead. Thus would lack a stealth modifier, which does matter quite a lot.
I would say that clip doesn't suffice. Also one statement from a guy on mmochamp doesn't prove much, his word shouldn't hold any more value than any of ours. For all we know all of the instances where he experiences the issues he does, might be from what I just explained. High stealth detection / low stealth modifiers, where opponents never lose sight of him at all. 

Personally, I always ran with several stealth modifiers and probably have some habits of moving off-center from people when I vanish due to having played rogue since closed US beta. I quit playing rogue around the start of Season 4, but I can honestly say I never had that third option happen to me. Where you vanish something else than blind, and you actually get hit by it + it breaks the vanish. I always played with low latency not sure if that would play any role.

Either way, I would say there must be more occurrences out there if this happens. Would be indisputable proof if we caught a video of someone actually doing this to an enemy, because then we can see if he ever loses him as a target at all. 
And if we find that it happens, then we need to find out why this was so rare on retail but happens about every duel on Corecraft.

**Comment by DarkenRal** [comment] 2016-03-03 01:44
> Well I know that if you have high stealth detection, heigthened senses + engi goggles if a rogue vanishes in front of you, you can still see him.

No, you can't. Read about how stealth and stealth detection works first at least! Count stealth lvls of vanished rogue and your max stealth detection and you'll understand why you are wrong. Vanish can be broken by enemy melee attacks (both normal attacks and instant melee abilities) and it was allways like this. Even more, you could break your own vanish with your white melee attack (unintentionally).

**Comment by ccnim** [comment] 2016-03-03 01:59
"ofc, if it breaks vanish (it was hemo hit into vanish; you can also evade melee atacks, same way you evade blinds and ofc vanish will be broken but no damge and no debuff)."

But in the link I provided he does get a debuff as well.

**Comment by DarkenRal** [comment] 2016-03-03 02:05
> But in the link I provided he does get a debuff as well.

Yes, it works same way as Vanish-Blind and Blind-Vanish. If you press Vanish first and your opponent press Hemorrhage (or any "instant" melee/ranged ability) - your vanish will be broken and you'll get damage and debuff (that's what happened in the video at that moment). If your opponent press his ability first and you press your Vanish second - you'll "evade" his attack (both damage and debuff) but your Vanish will still be broken.

**Comment by ccnim** [comment] 2016-03-03 02:22
Indeed, that is how spell queue would handle it but we never had any occurrences of it happening until the vid I linked. Some people thought it didn't leave a debuff which would then have been an exception to the spell queue. However this video seems to confirm that it can happen.

Now I'm not quite sure if I should close this issue or not since this issue seems to be a bit all over the place. Could anyone specify what the bug is here?

**Comment by DarkenRal** [comment] 2016-03-03 02:31
@ccnim There are no bug here, there are just some naive rogues who vanishing in melee range and think that their vanish should not be broken :)

edit: or actually as nullv0id said:

> What is the actual bug report here? Could someone summarize the issue that's reported, or could OP edit his post?
> 
> @ccshiro 
> In post 1 OP said melee hits were breaking vanish too often. No proof yet.
> In post 4 OP said resisted spells were also breaking vanish. I posted patch notes as proof this should not happen.
> 
> Rest seemed to be off-topic discussion, on blind/stuns breaking vanish which seems to be working as intended.

**Comment by Ickler** [comment] 2016-03-03 04:29
@DarkenRal I don't care what the stealth mechanics and detection says (and yes I know how it's supposed to work, better than you if you base yours off of Wowwiki which has it wrong), if you're straight in front of someone and close you can vanish and that person will still see you if he has various detection. It used to happen, I did play a lot alongside warlocks and had goggles so it might have only been in those cases, I can't recall that specifically. Why that happened, that's a different story in itself. 
But in general I'm talking from experience not out of my ass, if I don't remember something very clearly I won't make a statement about it without adding an element of uncertainty. 

About melee attacks and your own attacks there was a time when this was an issue yeah. But it seemed to come and go "magically"... Probably another one of Blizzards many undocumented changes / fixes. And you just used a /stopattack macro with your vanish to avoid that. 

Anyway I suggest you go try some rogue vs rogue duels on Corecraft if you think there's no issue here. Because as it stands, Vanish on CC is next to useless in certain situations and you don't even have to be slightly good to break someones vanish in devastating fashion.

From playing early on and through wotlk very actively, I can easily say there were many subtle changes to the game and vanish wasn't excluded from those. If the old forums were still accessible there would be tons of good stuff we could read up on about that as well. Vanish was always a hot topic and about how it "broke". 
All I'm asking is that it won't be much worse than it ever was, because if you do PvP as a rogue you rely on it big-time. 

And don't just shrug it off by saying you shouldn't vanish in melee range, everyone knows that's not ideal in any case. However if we're speaking arena, you more often than not do not have a choice about it. And if the vanish is broken, you would often lose that game because of that. So it is a **Very big deal**. Which is why I'm pressing hard to make sure this one is correct.

**Comment by Schaka** [comment] 2016-03-03 08:20
Personally, I suspect that this has to do with the small amount of time where you can see the vanish buff being applied to your opponent and him disappearing. When I last played on the test server, this time window seemed unsually large (on retail, when I played as and against rogues, it was usually much shorter - anecdotal). 

It might be, that auto attacks during this window (and spell casts) aren't stopped as they're supposed to be. It might be that all attacks should stop instantly, before the vanishing rogue even disappears from sight. 

I specifcally remember when 3.0.2 came out and people played it, how important vanish not breaking was for mage/rogue. I remember watching them play and playing against them and having guildies complain, if it happened. But it definitely wasn't as frequent as "80% of vanishes in melee range". That's including the /stopattack for your own autohits of course. Not that I see the point of purposely recreating bugs if we're not having seal twisting anyway.

**Comment by DarkenRal** [comment] 2016-03-03 12:55
@Ickler
You're vanishing in melee range. Just this part already shows that you don't understand or don't know anything about Vanish and it's mechanics at all. Even when i played on retail (3-4 seasons) there was a general rule that every rogue were trying to follow (including me; this rule was the same back in vanila and you could break your vanish with your own attack even back in vanila and in tbc and even stopattack doesn't helps that much): **NEVER VANISH IN MELEE RANGE**. If you do - get ready that your vanish will be broken by someone melee attack/ability or by your own attack with a very high chance. Do you already forgot how often pets (especially hunter's) were breaking Vanish? If you didn't time your Vanish ideally - at least 50% of your vanishes were broken. It has nothin to do with detections, if rogue already vanished - you couldn't see him even if you're human warlock with Paranoia, eng goggles with +18 detection, Elixir of the Searching Eye, your racial and rogue has no talents and enchants to increase his stealth lvl. But you could broke his Vanish with any instant ability before he fade away in stealth. If you just throw your Vanish in melee range vs melee opponents - get ready to lose it very often.

@Schaka 

> It might be, that auto attacks during this window (and spell casts) aren't stopped as they're supposed to be. It might be that all attacks should stop instantly, before the vanishing rogue even disappears from sight.

This is wrong, auto attack stops only because of the loss of the target (rogue stealthed). However, you might be right about time when you can see opponent with a Vanish buff. You can watch here https://youtu.be/xF4Rx1sQYQU?t=91 that rogue is still visible with stealth and vanish buff at least for 0.2-0.3 sec (maybe even more, i don't know how to measure time accurately there) before the target fades from him (means he became stealthed). Any attack (melee or ranged if it has no travel time), if it hits or even if it's just queued for a cast during that time will break Vanish. Anythin that hits rogue during that time will be evaded, anythin that was queued during that time will have it's full effect but in any case vanish will be broken.

You can try to record short video where rogue just cast his vanish in duel, upload it on Youtube and try to watch it on x0.25 speed and compare it to Neilyo movie. Maybe it'll show different times. This is the only possible bug here.

**Comment by ccnim** [comment] 2016-03-03 18:33
Spells resisted wont break vanish, tested it on the test server. 
And as the other bug reported is too vague and has more or less been shown to not be a bug I will close this issue.

**Comment by justinbeaver** [comment] 2016-03-03 18:33
@DarkenRal @ccnim 
still nothing is clear about resist and stealth/vanish

> Patch 2.0.3 "Resisted spells will no longer break "Stealth"/"Vanish"."
> But it happens far from 2.0.3 in season 3, 2.3.0+.
> https://www.youtube.com/watch?v=t8iiLNszJpU&feature=youtu.be&t=833

https://github.com/ccshiro/cc-buglist/issues/1122#issuecomment-133861030

> regarding resist breaking stealth in that video, it could be that cloak and regular spell resists act differently, since cloak = miss spells(which displays as resist) and resistance = resist, maybe normal resists should break stealth but misses shouldn't

https://github.com/ccshiro/cc-buglist/issues/1122#issuecomment-136371074

**Closed as completed by ccnim** 2016-03-03 18:33 UTC
Labels: invalid

**Comment by DarkenRal** [comment] 2016-03-03 18:53
@justinbeaver Patch 2.0.3 "Resisted spells will no longer break "Stealth"/"Vanish". This is enough. What you see in the video is just not complete fix (they tried to fix it but missed some bug).
@ccnim Resists should not break normal stealth also (not just vanish).
