### ISSUE TITLE
NPC's at pit commander standing wrong

### ISSUE THREAD

**Issue by PatchnotesTBC** [ccshiro/cc-buglist#1183] opened 2015-08-09 05:15 UTC
So i flew by and saw that one of the packs had manage to stand ontop of each other instead of in a formation like the others

Screens:
http://i.imgur.com/vwP9469.jpg
http://i.imgur.com/ZVuPqCH.jpg

**Comment by ConfusedCC** [comment] 2015-08-09 12:10
duplicate of #1016

**Closed as completed** 2015-08-14 02:37 UTC
Labels: duplicate
