### ISSUE TITLE
Character displacement

### ISSUE THREAD

**Issue by mrtveit14** [ccshiro/cc-buglist#101] opened 2015-01-18 00:02 UTC
My camera angel sometimes just turn 180 degrees for no reason when moving. I have one friend that does not have the same problem and one that does. I do not experience this on other private servers nor in retail so there is problem.

**Comment by Bearmanpig** [comment] 2015-01-18 00:06
There is a keybind that allows you to flip the camera to face backwards, maybe this is causing it? I haven't seen this problem. Also, camera behaviour is done clientside and not serverside.

**Comment by mrtveit14** [comment] 2015-01-18 00:10
I have never had this problem ever before on retail or in another private server. Been looking for the keybinding you are talking abiout, but cant find it

**Comment by ShuTestCC** [comment] 2015-01-18 00:23
I can confirm this. It randomly happens to me, too. I usually move by holding down both mouse buttons and then suddenly the camera flips 180° and before I know it I run the opposite way. With the same client and same settings I play on 2 other private servers and this issue is a first for me.

Do you, OP, move by holding both mouse buttons, too? If so, it needs to be tested whether keyboard can also cause this. My guess would be -no- but I have yet to test it. Will do tomorrow!

**Comment by mrtveit14** [comment] 2015-01-18 00:36
I only move using the keyboard. It has happened several times for me and my friends and we have never had this experience before today.

**Comment by ShuTestCC** [comment] 2015-01-18 00:44
Have you been to previous tests? I haven't; at least I haven't run around enough to trigger the bug last time. Just curious about if that's a fresh bug or an old one.

**Comment by mrtveit14** [comment] 2015-01-18 01:15
I have never been to a private server test before, so am im the same shoes as you.

**Comment by Iliana-sc** [comment] 2015-01-18 02:05
probably a duplicate of #62

**Closed as completed** 2015-01-18 02:12 UTC
Labels: duplicate
