### ISSUE TITLE
Shadow Labyrinth Grandmaster Vorpil

### ISSUE THREAD

**Issue by Lephidiles** [ccshiro/cc-buglist#2028] opened 2015-11-14 14:33 UTC
The voidwalkers that spawn during this boss fight seems to be moving to fast (almost double movement speed).
From memory they should be moving a lot slower.

Quote:
 Void Rift and Void Traveler adds Edit

When Vorpil is pulled, he will open 5 Void Rifts, one to the north, one to the east, one to the west, and two to the south. Each Void Rift will slowly spawn Void Travelers (Voidwalkers). The Void Travelers move very slowly towards Vorpil and have ~2500 health. Upon reaching Vorpil, they will explode dealing ~1500 damage in a ~10yd radius, and also heal Vorpil for 4% of his health. 

http://wowwiki.wikia.com/wiki/Grandmaster_Vorpil

**Comment by KimmoKM** [comment] 2015-11-14 18:04
I checked the earliest videos I found in Youtube and the elementals do seem to move quite slowly in them as well. Is that slower than currently in Corecraft? Maybe. When I did SL, I didn't pay any particular attention to their movement speed.

**Comment by ccshiro** [comment] 2015-11-14 19:21
Duplicate of #1925.

**Closed as completed by ccshiro** 2015-11-14 19:21 UTC
Labels: duplicate
