### ISSUE TITLE
Area: Skettis

### ISSUE THREAD

**Issue by Argonn** [ccshiro/cc-buglist#146] opened 2015-01-18 10:58 UTC
When i was trying out the Skettis area, i noticed the area 'shaking'.
Some of Skettis monsters area taking invisible damage, and are Evading all my attacks.
They drop from 100%-90% and back to 100%, but are un-attackable. They do not have a attacking target (target the mob, and pressed 'F' without succes).

**Comment by Iliana-sc** [comment] 2015-01-18 11:04
edit: removed wrong comment, sorry!

**Comment by Argonn** [comment] 2015-01-18 11:31
This is nothing like monsters falling trough anything. These where outside monsters taking invisible damage (you can hear the _hit_ sound being played every 0.1.second).
And _blinking_ all over the place or just frozen in place, without reacting to anything a player does to him. They do not agro or attack you.

**Comment by ccshiro** [comment] 2015-01-18 14:09
Actual duplicate of #126

**Closed as completed** 2015-01-18 14:09 UTC
Labels: duplicate

**Comment by Iliana-sc** [comment] 2015-01-18 14:14
you're right sorry, I accidentally linked the wrong bug, #126 is indeed what I meant to reference
