### ISSUE TITLE
[Blood Furnace][Heroic] Last Boss Adds can be pulled one by one

### ISSUE THREAD

**Issue by Piranhaz** [ccshiro/cc-buglist#1362] opened 2015-08-13 19:08 UTC
As in description said, the adds from the last boss can be pulled back one by one. Also the boss didnt add automatically when all were dead i think but not 100% sure about that. The adds should be linked.

**Comment by ghost** [comment] 2015-08-13 21:45
#duplicate of #1339

**Closed as completed** 2015-08-14 02:07 UTC
Labels: duplicate
