### ISSUE TITLE
Stonescythe Alpha is "Invalid target" while attacking me

### ISSUE THREAD

**Issue by netherspite** [ccshiro/cc-buglist#327] opened 2015-04-01 20:22 UTC
I was not able to attack the Stonescythe Alpha at the entrance to the cave with the Blacktalon the Savage (elite mob for the Wanted quest) with the direct spells. I could hit him with AoE though.
He successfully noticed me and started attacking me on sight.
After the server crash and restart he was in normal state again.
![wowscrnshot_033115_203350](https://cloud.githubusercontent.com/assets/5777848/6951708/e580af1a-d8c5-11e4-84a2-dbec21f090c6.jpg)

**Comment by ccnim** [comment] 2015-04-02 14:09
Couldn't reproduce this and it looks a lot like the ALT bug (due to you being able to AoE) and therefor I will invalidate it. 

The ALT bug happens when you tab in and out of the game during the loading screen and will make the game think you are holding down your ALT key. If this happens again tap ALT once and it should be fixed.

**Closed as completed by ccnim** 2015-04-02 14:09 UTC
Labels: invalid
