### ISSUE TITLE
[Hunter] Flare has no travel time

### ISSUE THREAD

**Issue by Aasamath** [ccshiro/cc-buglist#1451] opened 2015-08-21 15:18 UTC
On that clip you can see a hunt in the background launching a flare 
https://youtu.be/FFNcdVEwzKs?t=99
On the video the flare travels a fair distance, then the light zone on the ground appears.
On Corecraft whatever the distance you're at, the aoe on the ground will appear instantly (not counting the little delay i saw, since it's the same whatever the range). 
I can't prove with this clip that the spell effect should also be delayed depending on the distance, but i think it should be looked into.

**Comment by ccshiro** [comment] 2015-08-21 15:32
Duplicate of #756.

**Closed as completed by ccshiro** 2015-08-21 15:32 UTC
Labels: duplicate

**Comment by Aasamath** [comment] 2015-08-21 15:33
sowy :)
