### ISSUE TITLE
AFK message is spamming me.

### ISSUE THREAD

**Issue by Rafuros** [ccshiro/cc-buglist#1903] opened 2015-10-04 20:02 UTC
This encountered on your test server, and when my friend "Happystab" (he is on my friends list) is away from keyboard and im not even in party with him i will get spammed with afk messages.

I tested this with him next to me and i took the timer. it seems that every 15-20 seconds a new message pops in, i tested this for 2 minutes and i got 7 messages. at 1 minute 30 seconds i had gotten 5.

![wowscrnshot_100415_215814](https://cloud.githubusercontent.com/assets/14223192/10269921/867b93c6-6ae3-11e5-8674-a5dc8967bb04.jpg)
![wowscrnshot_100415_215840](https://cloud.githubusercontent.com/assets/14223192/10269922/8b80447a-6ae3-11e5-9c57-04c3fb55a51e.jpg)
![wowscrnshot_100415_215857](https://cloud.githubusercontent.com/assets/14223192/10269923/8d0b0578-6ae3-11e5-8190-dfc502583053.jpg)
![wowscrnshot_100415_215915](https://cloud.githubusercontent.com/assets/14223192/10269925/8ef4f164-6ae3-11e5-92bf-a9278b61dfb8.jpg)
![wowscrnshot_100415_215942](https://cloud.githubusercontent.com/assets/14223192/10269929/906c29c2-6ae3-11e5-8815-717a2e12cac7.jpg)
![wowscrnshot_100415_215955](https://cloud.githubusercontent.com/assets/14223192/10269930/9271ce52-6ae3-11e5-8cc0-602675128e9f.jpg)
![wowscrnshot_100415_220010](https://cloud.githubusercontent.com/assets/14223192/10269933/97a7b2a6-6ae3-11e5-9258-a8e1da64bb98.jpg)

**Comment by Rafuros** [comment] 2015-10-04 20:31
https://drive.google.com/open?id=0BziueTJbUhkRZngzMDhJYlZCSTg here is a video of this bug.

**Comment by ccshiro** [comment] 2015-10-04 21:19
Duplicate of #807.

**Closed as completed by ccshiro** 2015-10-04 21:19 UTC
Labels: duplicate
