### ISSUE TITLE
Last Boss Bulwark

### ISSUE THREAD

**Issue by ghost** [ccshiro/cc-buglist#1444] opened 2015-08-20 19:14 UTC
Adds in this encounter dont attack at the same time, but need to be pulled one by one.

it should work like this:

u pull one add, all come and join the fight, boss enters combat after all adds are down.

**Comment by ccshiro** [comment] 2015-08-20 20:08
Duplicate of #1242.

**Closed as completed by ccshiro** 2015-08-20 20:08 UTC
Labels: duplicate
