### ISSUE TITLE
[Dungeon] Keli dan the breaker mobs are not linked to each other

### ISSUE THREAD

**Issue by ghost** [ccshiro/cc-buglist#1339] opened 2015-08-12 23:02 UTC
this is actually weird since the next time we tried it (after the time) they all worked perfectly

Steps to reproduce: we dindt do anything out of the ordinary so  i guess im not able to explain

1st try: https://www.youtube.com/watch?v=UwJa0OBjILw&feature=youtu.be
![mobs unlinked](https://cloud.githubusercontent.com/assets/13721369/9238995/b8721e5a-4157-11e5-8778-31c871e6c323.png)
![captura de pantalla 2015-08-13 a las 0 25 07](https://cloud.githubusercontent.com/assets/13721369/9238996/b88f06c8-4157-11e5-9101-deab3b4ba7e3.png)
2nd try:https://www.youtube.com/watch?v=qYPm31xCaHE&feature=youtu.be

**Comment by Magnumspb** [comment] 2015-08-14 06:45
confirm same issue

https://youtu.be/utd_AaTQRXg?t=42m36s

**Comment by ghost** [comment] 2015-08-14 10:56
@Magnumspb exact same issue :)
Apparently it always happens in the first pull only, if you wipe and retry, mob's will work correctly

**Comment by ccshiro** [comment] 2015-08-15 18:11
Duplicate of #1242.

**Closed as completed by ccshiro** 2015-08-15 18:11 UTC
Labels: duplicate
