### ISSUE TITLE
Movement bug Botanica hc (Laj and endboss trash)

### ISSUE THREAD

**Issue by abuescher** [ccshiro/cc-buglist#1355] opened 2015-08-13 16:51 UTC
Laj doesnt stand upon her place after resetting the encounter but in it:

http://imgur.com/UvctRV8

Endboss trash is still bugged (evade n stuff - already seen in another issue)

**Comment by ccshiro** [comment] 2015-09-18 15:52
Duplicate of #1178.

**Closed as completed by ccshiro** 2015-09-18 15:52 UTC
Labels: duplicate
