### ISSUE TITLE
Bugged shadowhide brute

### ISSUE THREAD

**Issue by Metzalon** [ccshiro/cc-buglist#192] opened 2015-01-18 16:46 UTC
There is a bugged shadowhide brute in front of teh Galardell valley in Redridge mountains.
The mob is directly in front of the cave it is standing still and doesnt do anything, if you attack it you can't do damage and it keeps evading.

**Comment by FurioCC** [comment] 2015-01-18 17:16
Should be same issue as #126

**Comment by ccshiro** [comment] 2015-02-22 17:00
Duplicate of #122 and #92.

**Closed as completed by ccshiro** 2015-02-22 17:00 UTC
Labels: duplicate
