### ISSUE TITLE
Summoned adds of mobs disappear if the master is slain

### ISSUE THREAD

**Issue by Peter1337** [ccshiro/cc-buglist#1763] opened 2015-09-11 15:05 UTC
as the title says.

happened with all mobs in outland so far, f.e. the bloodelf mages at the path of conquest -> they summon two arcane mobs which explode after some seconds -> those diappear if the mage is slain prior to the selfdestruction

there are also mobs with already summoned adds/pets -> thos birdguys in blade's edge mountain f.e. that have a hawk with them -> slay the birdguy -> hawk disappears

blood elves on hawkstrider (like Eclipsion Bloodwarden in Shadowmoon Valley) spawn their hawkstrider after being defeated. those hawkstrider do NOT attack themselves and despawn after ~3-5sec if one does not attack them.

**Comment by ccshiro** [comment] 2015-09-15 16:38
Duplicate of #1058.

**Closed as completed by ccshiro** 2015-09-15 16:38 UTC
Labels: duplicate
