### ISSUE TITLE
Sending mail

### ISSUE THREAD

**Issue by Lephidiles** [ccshiro/cc-buglist#1265] opened 2015-08-10 20:59 UTC
First mail you send from one char to another from one mail box contains no items when it arrives.
Secound mail you send from same mail box to same char usually contain the item (as in i have never seen it go away)

(got video if needed)

**Comment by ConfusedCC** [comment] 2015-08-10 22:18
duplicate of #1167

**Closed as completed** 2015-08-11 15:42 UTC
