### ISSUE TITLE
Druids Swipe hitting targets behind you

### ISSUE THREAD

**Issue by descendance** [ccshiro/cc-buglist#1021] opened 2015-07-07 07:20 UTC
Feral druids swipe also hits targets that are directly behind you.

It should only hit targets in front of you.

![wowscrnshot_070715_090030](https://cloud.githubusercontent.com/assets/5084397/8540732/93997682-2488-11e5-9683-84669bd3b14b.jpg)
![wowscrnshot_070715_090041](https://cloud.githubusercontent.com/assets/5084397/8540733/93a0e606-2488-11e5-8ae7-c4c118246ed1.jpg)

This was added in patch 3.0.2. 

http://www.restokin.com/2009/03/swipe-i-can-hit-you-with-mah-tail/

http://wowwiki.wikia.com/Patch_3.0.2   what it says "Swipe now affects targets within a range".

This is probably a duplicate of https://github.com/ccshiro/cc-buglist/issues/902

**Comment by ccshiro** [comment] 2015-07-10 17:49
As you said, probably duplicate of #902 and #817.

**Comment by Barroth** [comment] 2015-07-10 18:05
as of 3.0.2 the spell effect changed:

From TARGET_CHAIN_DAMAGE, NO_TARGET to TARGET_CASTER_COORDINATES, TARGET_ALL_ENEMY_IN_AREA

Essantially after 3.0.2 it works like an arcane explosion with 8y range.

**Comment by ccshiro** [comment] 2015-07-11 16:21
I will close this as duplicate of #817, as it's going to have the same solution.

**Closed as completed by ccshiro** 2015-07-11 16:21 UTC
Labels: duplicate
