### ISSUE TITLE
Camera bugs when mage blinks

### ISSUE THREAD

**Issue by Dxerk** [ccshiro/cc-buglist#221] opened 2015-01-18 18:30 UTC
After playing some arenas and dueling mages. I noticed that every time they blink my camera automatically changes direction and is "following" the mage. 
This seems to happen only when I'm holding down my mouse button. I don't know if it's intended, but it's annoying!

https://www.youtube.com/watch?v=44PcSGNRXl0&feature=youtu.be

**Comment by FurioCC** [comment] 2015-01-18 18:33
Most likely related to #62

**Comment by ccshiro** [comment] 2015-01-18 19:46
Duplicate of #62.

**Closed as completed by ccshiro** 2015-01-18 19:46 UTC
Labels: duplicate
