### ISSUE TITLE
Orc racial: bloodfury displayed with lvl 1 attributes

### ISSUE THREAD

**Issue by Piranhaz** [ccshiro/cc-buglist#1297] opened 2015-08-11 15:06 UTC
As mention, the orc racial "bloodfury" has a lvl 1 tooltip (6 attackpower). when u activate it, the buff says 282.

**Comment by Pinhastest** [comment] 2015-08-11 15:52
Its a known bug

**Comment by nz54445** [comment] 2015-08-11 16:52
Duplicate of #175

**Closed as completed** 2015-08-11 21:25 UTC
Labels: duplicate
