### ISSUE TITLE
[Arcatraz] Dalliah the Doomsayer & Wrath-Scryer Soccothrates Encounters

### ISSUE THREAD

**Issue by Roarek** [ccshiro/cc-buglist#851] opened 2015-07-05 07:22 UTC
When you first enter their room, Dalliah and Soccothrates should have a big voiced argument like an old married couple in /y chat. We didn't see the /y in chat and we didn't audibly hear the dialogue. 

When fighting Dalliah, none of her spells were interruptable, including her heal. The heal is supposed to be interruptable - I think all her spells are supposed to be except for the whirlwind, but I have proof of the heal being counterspelled on retail BC: https://www.youtube.com/watch?v=fGxe6d_w6b4&t=3m16s

Soccothrates' fire trail was not forming fully as it should cover the entire path of his charge, rather than just the start of it and the end of it in flame. Proof from retail BC: https://www.youtube.com/watch?v=fGxe6d_w6b4&t=3m45s

Attached here is a video of these encounters on the server during this test phase: https://drive.google.com/file/d/0B4ZqMxVDoS9Kd2szRGtkUkxubjg/view?usp=sharing

**Comment by FurioCC** [comment] 2015-07-05 10:35
@Roarek Yesterday we did heroic Arcatraz and heal was interruptable and working as intended.

**Comment by Roarek** [comment] 2015-07-05 20:18
That may have been the case for you, but it doesn't explain why my kick was ineffective on every cast I attempted to kick for. My guess would be it's latency related in that case, except then my kick should have affected the next immediate cast that was made at one point in that video and it did not. See @ 1:06, it looks to me like I get the kick at the very last 10% of the cast. Assuming I missed this due to latency, that next immediate cast would probably have been interrupted instead. Mind you, my latency is around 90 ms. Could it have anything to do with the cast bar being off perhaps?

If I'm the only one it's been a problem for (though the other rogue in my group agreed he wasn't able to get an effective kick for anything but the shadow wave) then maybe I was just fucking up on timing and latency.

**Comment by KevinTyrrell** [comment] 2015-07-06 03:10
Another thing is that the Soccothrates fight is really off in some regard. 

When he does the knockback ability, he is either supposed to say "On Guard" or the "Defend yourselves, for all the good it will do". I can't quite remember if the mob actually played the audio clip for "On Guard" or "Defend yourselves" so if someone can check that, then that would be good. 

During the Knockback ability, he is supposed to lay fire in the path of the target. Currently he lays the fire in the path he takes. I think this is the wrong way of doing it. 

On Corecraft: https://drive.google.com/file/d/0B4ZqMxVDoS9Kd2szRGtkUkxubjg/view   (at 3:53) notice how fire is only spawned from where he was and when he ends up. 

In Retail: https://youtu.be/fGxe6d_w6b4?t=243, notice how it creates a PERFECT line.

Solution: 
Maybe have some sort of check where the player being looked at is, and where the boss currently is:
Ex. Player at 52,42                      Boss at                    168, 199
Then have it do the distance between two points formula
Distance = 195.20502 units

Then figure out the width of the fire, ex: 30 units

Divide distance by the width of the fire. 
double frequency = 195.20502 / fireWidth;

Then just figure out how to tell what direction the player is in and spawn them in a line towards him. Shouldn't be too bad.

**Comment by KevinTyrrell** [comment] 2015-07-06 03:54
Also one thing to add, in the Paladin tank video, whenever Soccothrates is attacked, he makes a 'ugh' sound. I do not believe this is present in Corecraft as of now.

**Comment by ccshiro** [comment] 2015-07-11 21:26
RP pre-event:
Yells work fine, sound does seem to be missing. Will check.

Interrupting heal:
Tested and can interrupt the heal with Rogue kick just fine.

Soccothrates fire trail:
Is indeed not working as it should, will look at it.

Soccothrates yell on charge:
The yell appears and works.

Soccothrates ugh:
The sound an NPC makes when hit is client-side. As for the ugh, I can hear it loud and clearly.

Conclusion: The only bugs I can see in here: the charge + trail is not working correctly & the sound for pre event is missing.

**Comment by ccshiro** [comment] 2015-07-12 23:08
@ccnim The charge mechanic is now fixed. All that remains is adding sounds to the pre-event. That's in the sc2dev database.

**Closed as completed** 2015-07-13 17:28 UTC
Labels: bug, cannot reproduce
