### ISSUE TITLE
Classic [Quest] A Bundle of Trouble

### ISSUE THREAD

**Issue by RealZwox** [ccshiro/cc-buglist#1696] opened 2015-09-07 19:00 UTC
Elwynn Forest

Bundle of Wood dont disapear when you !! SHIFT- LOOT !! them. When you rightclick on them normaly and loot them they disapear.

**Comment by KimmoKM** [comment] 2015-09-08 09:08
As it's possible to turn autoloot on and off without need for shift-looting, it's probably worth clarifying that autoloot causes the bundles not to disappear while looting them manually causes them to fade off immediately. Actually, autolooted bundles also seem to disappear, but only with ~20s delay.

**Comment by ccshiro** [comment] 2015-09-21 19:39
Duplicate of #434.

**Closed as completed by ccshiro** 2015-09-21 19:39 UTC
Labels: duplicate
