### ISSUE TITLE
Stuck/Evade Skettis Eviscerator

### ISSUE THREAD

**Issue by tekknomaggus** [ccshiro/cc-buglist#187] opened 2015-01-18 15:56 UTC
I found at least 3 stuck mobs in the skettis area. 1 in the north west on a bridge and another one near that at the lake. the terrain kind of shook there.

**Comment by ccshiro** [comment] 2015-01-18 15:58
Most likely a duplicate of #146 and #126.

**Closed as completed by ccshiro** 2015-01-18 15:58 UTC
Labels: duplicate
