### ISSUE TITLE
Cleave hitting targets behind you

### ISSUE THREAD

**Issue by KevinTyrrell** [ccshiro/cc-buglist#902] opened 2015-07-05 15:04 UTC
Problem: A warrior's cleave is hitting targets behind the caster. Allegedly this does not happen on retail. More research likely needed.  
How to reproduce: N/A
Solution: unknown
Proof: http://www.twitch.tv/hatefiend/b/675593523?t=1h19m45s
Burning crusade proof: could not find

**Comment by ConfusedCC** [comment] 2015-07-05 16:49
wiki link: http://wowwiki.wikia.com/Cleave?direction=prev&oldid=814499
Targets/Positioning: Two targets/front

**Comment by ccshiro** [comment] 2015-07-10 17:49
Duplicate of #817.

**Closed as completed by ccshiro** 2015-07-10 17:49 UTC
Labels: duplicate
