### ISSUE TITLE
Scarlet Monastery Cathedral with Corrupted Ashbringer yields no scripted event.

### ISSUE THREAD

**Issue by KevinTyrrell** [ccshiro/cc-buglist#1174] opened 2015-08-09 01:00 UTC
Problem: walking into SM Cathedral with the Corrupted Ashbringer does not make the player friendly to Scarlet Monastery and does not consist of any event.
How to reproduce: Equip Corrupted Ashbringer, observe the buff on yourself, then walk into Scarlet Monastery Cathedral. 
Solution: unknown
Proof: http://www.twitch.tv/hatefiend/c/7017088?t=02s
Burning crusade proof: https://www.youtube.com/watch?v=fAW-EgWu3BU

**Comment by nullfoxh** [comment] 2015-08-09 01:34
Duplicate of: https://github.com/ccshiro/cc-buglist/issues/490

**Closed as completed** 2015-08-09 10:01 UTC
Labels: duplicate
