### ISSUE TITLE
Berserker rage doesn't give incapacitate immunity

### ISSUE THREAD

**Issue by Aasamath** [ccshiro/cc-buglist#1407] opened 2015-08-16 23:14 UTC
I tried getting sap, fear and gouge with Berserker rage buff, gouge isn't affected by the immunity.
Though berserker rage correctly removes it (aswell as fear and sap).

**Comment by ccshiro** [comment] 2015-08-21 17:33
Duplicate of #1094.

**Closed as completed by ccshiro** 2015-08-21 17:33 UTC
Labels: duplicate
