### ISSUE TITLE
Mob fell through water & disappeared when killed

### ISSUE THREAD

**Issue by pjce** [ccshiro/cc-buglist#725] opened 2015-06-10 16:05 UTC
skip to 1:03 https://drive.google.com/open?id=0BxExaa9wBWZAdC1pOFpxemRVbnc&authuser=1

Only did this one once I'm afraid as I was out of time (sorry!) so not sure if it may have been related to the escort event I had triggered.

**Comment by ccshiro** [comment] 2015-06-10 19:29
Duplicate of #665.

**Closed as completed by ccshiro** 2015-06-10 19:29 UTC
Labels: duplicate
