### ISSUE TITLE
[H] Shadow Labs: Issues and Impressions

### ISSUE THREAD

**Issue by Escape243** [ccshiro/cc-buglist#131] opened 2015-01-18 06:07 UTC
First room; first big area right after zone in, mixed mobs, no boss.
-All the pulls we did seemed solid and working as intended. The number of mobs, their placement and movement appeared accurate.

Second room; next big area after passage, channelers and large fel guard patrols. Boss; Ambassador Hellmaw.
-I don't remember there being 4 channelers per pillar. There could have been and maybe there was in the heroic mode and only 3 in the normal mode? If someone could log onto retail and confirm this that would be great.
-Sometimes a channeler would get stuck and just stand there inactive for approximately 20 seconds. Essentially CCing itself.
-Boss appeared to be working properly.

Third room; next big area, large packs of mixed mobs and Malicious Instructor patrols, Boss; Blackheart the Inciter.
-The Instructor patrols seemed a bit off to me in terms of their placement, I remember all 3 of them arriving at points that they could be easily pulled before aggroing or killing any of the other static packs. Again I could be misremembering, this needs to be confirmed on retail.
-Cabal Deathsworn mobs would sometimes get stuck (similarly to the Channelers in the previous room) and sit there and stare at our group.
-Blackheart the Inciter - Player damage while mind controlled seemed much too high. This is very hard to judge but it definitely felt out of hand. Also, floating nameplates of party members were sometimes the friendly blue/green color while MCed instead of red. I was happy to see that remaining trash left alive in the room pulls when the boss is engaged, which is correct.

This was as far as we got, we did not kill the 2nd boss.

**Comment by Dailybs** [comment] 2015-01-18 06:49
our 5 man team got killed 5 times before we tactically disbanded in Botanica HC :D all seems to wortk fine there though.

**Comment by Catfishs** [comment] 2015-01-18 07:27
I think the "mobs getting stuck" is related to crowd control effects somehow expiring and making the mob passive. #91

**Comment by Kall-DestinyAwaits** [comment] 2015-01-18 13:09
Major bug: During 2nd boss fights you can die and go inside to instance while encounter is still in progress (This can work on other boss fights to)
Minnor bug: Arcane Conteiner next to Murmur (for Karazhan chain) spwning 2x npc First Fragment Guardian = more then 5 people can get key from 1 run

**Comment by descendance** [comment] 2015-01-18 15:13
During the 2nd boss encounter(Blackheart the Inciter) you could in fact die and run back on retail so it is not a bug.

comments from back than: http://web.archive.org/web/20070718133653/http://wow.allakhazam.com/db/mob.html?wmob=18667

also: http://web.archive.org/web/20070509054904/http://www.wowwiki.com/Blackheart_the_Inciter

Also worth noting that in the comments in the link above people mention that they would get MC'ed no matter where the were in the instance during the encounter. Be it next to the boss or at instance entrance etc.

**Comment by ccshiro** [comment] 2015-01-18 17:05
I read through the list (please in the future make one report per bug, that way we can use the bug tracker more easily to organize reports). From what I can see the listed CC bug is the only one that's actually broken -- the other reports are working as intended. Hope I didn't read over any, but closing this as duplicate.

**Closed as completed by ccshiro** 2015-01-18 17:05 UTC
Labels: duplicate
