### ISSUE TITLE
Vanish does not put you into Stealth when Stealth is on a cooldown.

### ISSUE THREAD

**Issue by Dusky1** [ccshiro/cc-buglist#2517] opened 2016-04-10 10:27 UTC
Simple as the title says. Vanish does not put you into stealth when your Stealth is on a cooldown. It should ALLWAYS put you into stealth.

[https://www.youtube.com/watch?v=KHT94SmNzVE]

**Comment by ccshiro** [comment] 2016-04-11 14:39
Duplicate of #2467. Fix just isn't on the test server yet.

**Closed as completed by ccshiro** 2016-04-11 14:39 UTC
Labels: duplicate
