### ISSUE TITLE
Fel Orc Corpse in The Assassin is not really corpse

### ISSUE THREAD

**Issue by netherspite** [ccshiro/cc-buglist#197] opened 2015-01-18 17:06 UTC
The target you have to turn the quest "The Assassin" in should be a corpse but he is not really a corpse.
Screenshot attached

**Comment by netherspite** [comment] 2015-01-18 17:07
![wowscrnshot_011815_122729](https://cloud.githubusercontent.com/assets/5777848/5793239/30b6dc08-9f45-11e4-8099-4059a08e9b13.jpg)

**Comment by Mustonen1** [comment] 2015-01-18 17:20
Duplicate of #60

**Comment by netherspite** [comment] 2015-01-18 17:25
True, had to write in comments to that issue. Thanks.

**Closed as completed** 2015-01-20 20:39 UTC
Labels: duplicate
