### ISSUE TITLE
Hunter pet disappearing (lost forever)

### ISSUE THREAD

**Issue by DaRealBoss** [ccshiro/cc-buglist#442] opened 2015-04-20 21:31 UTC
Hunter pet disappears and even after relogging is nowhere to be found, and you have to tame a new one. 

How to reproduce: Tame a pet. Mount up (I used my nether rocket cause its my only mount). Use ability Call Pet while your mounted on the ground; this should unmount you automatically and summon your pet. Mount up again. Un-mount. Pet is gone :(

**Comment by Chulain** [comment] 2015-04-20 21:35
confirmed, i lost mine too

**Comment by wonderchipstick** [comment] 2015-04-20 22:00
The pet was full on happiness? Maybe it just ran away because it's happiness level was not proper.

**Comment by sandfury** [comment] 2015-04-20 23:27
related to pet disappearing, I put my pet (which was happy bear in mind) inside scryer's pet stables but then he just completely disappeared, I could not call / revive him. I was neutral with scryer by the way.

**Comment by rsheep** [comment] 2015-04-21 10:25
@sandfury Stable-related pet disappearance will be fixed on a relog.
Stables are working mostly. The bugs are mostly visual and they will fix by themselves with a relog.
Still stables are bugged and many times you are not able to get pet back till a relog.
Stables need some bug-fixing to have them "blizzlike".

**Closed as completed** 2015-04-24 19:44 UTC
Labels: bug
