### ISSUE TITLE
Character pathing is going crazy in BG's. 

### ISSUE THREAD

**Issue by Sinergyy** [ccshiro/cc-buglist#140] opened 2015-01-18 10:01 UTC
From time to time, on any char you play in BG, when you walk, it suddenly changes your pathing to 180 degrees and you just start walking in the opposite direction. And the worse thing is that the camera follows it also, and you practically continue walking the way you came from. 

This happens especially in a fight, sometimes when I cast a spell, other times when I'm about to, and other times it just happens while simply walking. 

Not sure if anyone reported this but It happened on 3 people, different chars, different bg's already. So I guess it's happening to everyone. And it didn't happened before in previous tests.

Best regards.

**Comment by descendance** [comment] 2015-01-18 10:08
This is not related only to BG's. This happened to me while in OHF normal dungeon. No special circumstances, was only walking in front of the durnholde keep. 
Also happened to me while in the church with thrall(while escorting him after releasing him). 
Seems to happen randomly through the instance/world.
No idea how to reproduce it.
If it matters i use 'A' and 'D' keys to strife left and right, 'S' key to move forward and i rotate with right mouse click.

**Comment by Pronator** [comment] 2015-01-18 10:15
I have experienced this also, didn't quite realize it until now.  Sometimes its like you just do an instant 180.

**Comment by Iliana-sc** [comment] 2015-01-18 10:39
duplicate of #62

**Comment by Sinergyy** [comment] 2015-01-18 10:54
Tested it a little and realised we all get the bug in the same time. Everyone in a bg. Doesn't matter what we do, how we move, etc. And it's very often.

**Closed as completed** 2015-01-18 14:02 UTC
Labels: duplicate
