### ISSUE TITLE
Buggy movement after relog

### ISSUE THREAD

**Issue by Tasserski** [ccshiro/cc-buglist#294] opened 2015-03-31 21:18 UTC
Movement had some issues from time to time prior to crashes, preventing moving from a certain area. Seems to happen after every relog, but if you can find a way to move (hearthstone, blink, charge), it goes away. Video: http://ponkolauta.net/player.php?v=/WoW/src/1427824140366.webm&t=movement.webm&loop=1

**Comment by Chulain** [comment] 2015-03-31 22:09
confirmed, happened to me too

**Comment by ccshiro** [comment] 2015-04-01 21:02
This was very likely caused by the same code that caused the crash we had, which means this issue should be fixed already. If you notice it again in future tests, please reopen this.

**Closed as completed by ccshiro** 2015-04-01 21:02 UTC
