### ISSUE TITLE
[Mobs][Minor] Gan'arg Servant stuck in object, Hellfire Peninsula

### ISSUE THREAD

**Issue by Winns** [ccshiro/cc-buglist#237] opened 2015-01-19 10:15 UTC
Just a minor bug.

[Gan'arg Servan](http://www.wowhead.com/npc=16947/ganarg-servant) stuck in object and can't attack.
http://i.imgur.com/N0oJaTI.jpg

**Comment by KuroiKensai** [comment] 2015-01-19 10:31
I think this is global bug, not just this one mob. Some problems with geodata.

**Comment by ccshiro** [comment] 2015-02-18 01:08
Duplicate of #192 most likely.

**Closed as completed by ccshiro** 2015-02-18 01:08 UTC
Labels: duplicate
