### ISSUE TITLE
[LoS] "Target is not in line of sight" at the start of every horde BG

### ISSUE THREAD

**Issue by ghost** [ccshiro/cc-buglist#1212] opened 2015-08-09 20:13 UTC
self explanatory.

1.create a buffing class
2. go horde bg.
3.try to buff someone, even the own player

![bglos](https://cloud.githubusercontent.com/assets/13721369/9156701/d0905c52-3ee3-11e5-8cbb-a555bc6a6075.png)
![bglos2](https://cloud.githubusercontent.com/assets/13721369/9156702/d0983d28-3ee3-11e5-98b5-43ef6846b8bb.png)
![bglos3](https://cloud.githubusercontent.com/assets/13721369/9156704/d09a9fd2-3ee3-11e5-80e6-6ea628178d9d.png)
![bglos4](https://cloud.githubusercontent.com/assets/13721369/9156703/d099afb4-3ee3-11e5-9269-dc6d30d16605.png)

**Comment by ccshiro** [comment] 2015-08-15 17:50
Duplicate of #1199.

**Closed as completed by ccshiro** 2015-08-15 17:50 UTC
Labels: duplicate
