### ISSUE TITLE
Defencive stance pet

### ISSUE THREAD

**Issue by Lephidiles** [ccshiro/cc-buglist#931] opened 2015-07-05 20:54 UTC
When attacking a npc (hostile action) pet is suppose to start attacking as well not wait until master is attacked

https://www.youtube.com/watch?v=Yylhn3cpO0E

**Comment by Barroth** [comment] 2015-07-05 20:58
Retails pet behaviour is quite different from tbc, see http://wowwiki.wikia.com/Defensive?oldid=1432708

This is working as intended for tbc

**Comment by ccshiro** [comment] 2015-07-05 21:07
Duplicate of #864, as I told that guy: "No, you're thinking of the new assist mode that was added in patch 4.2."

**Closed as completed by ccshiro** 2015-07-05 21:07 UTC
Labels: duplicate, invalid
