### ISSUE TITLE
Shadow Labyrinth trash mobs

### ISSUE THREAD

**Issue by KevinTyrrell** [ccshiro/cc-buglist#901] opened 2015-07-05 14:57 UTC
**Cabal Shadow Priest (not the Hearthstone card!)
Problem: the mob will sometimes cast mind flay while moving
How to reproduce: unknown, speculated that it happens only when the mob is in the middle of running towards a target and also is told to cast mind flay at the same time. 
Solution: flag the mind flay he uses to require the caster to stand still while channeling.
Proof: http://www.twitch.tv/hatefiend/b/675593523?t=55s (occurs at 1 minute in), http://www.twitch.tv/hatefiend/b/675583832?t=42m51s (occurs at 42:52).
Burning crusade proof: not needed. pretty apparent that this is unintentional

**Cabal Cultist
Problem: speculation, may not actually be an issue, mob tethering doesn't reach nearby pack in one specific circumstance
How to reproduce: visit the spot shown in the video and try pulling the two cultists on the left. 
Solution: unknown
Proof: http://www.twitch.tv/hatefiend/b/675593523?t=35m34s
Burning crusade proof: cannot locate

**Multiple Creatures
Problem: mobs sometimes stand still in attack stance but do not fight back under certain circumstances
How to reproduce: POSSIBLY has something to do with distract. That is the common denominator between what I recorded. 
Solution: unknown
Proof: http://www.twitch.tv/hatefiend/b/675583832?t=9m38s (the mob with the 2Hander stands still), http://www.twitch.tv/hatefiend/b/675593523?t=45m51s (all four mobs in the row stand still after being distracted -- note they are in their sitting animation during the distract).

**Skeleton Trash Mobs
Problem: evade issue
How to reproduce: unknown, Rogue pulled and vanished. They were later pulled and walked over certain terrain. 
Solution: unknown
Proof: http://www.twitch.tv/hatefiend/b/675593523?t=46m54s (Rogue pulls mobs, skeletons later Evade)
Burning crusade proof: not needed

**Comment by KevinTyrrell** [comment] 2015-07-15 03:24
Note, these twitch vods will not stay up for more than two weeks.

**Comment by ccshiro** [comment] 2015-07-20 20:49
1) Confirmed bugged.
2) Doesn't seem like a bug.
3) Fixed in another report already.
4) Cannot reproduce.
As such, will look at number 1 and ignore the other 3.

**Closed as completed** 2015-07-21 17:22 UTC
Labels: bug
