### ISSUE TITLE
Mobs not attacking after breaking CC or Running Away In Fear

### ISSUE THREAD

**Issue by Winns** [ccshiro/cc-buglist#190] opened 2015-01-18 16:44 UTC
**Introduction.**
If caster mob does not have mana he will start attack in melee. If mob ([runner](http://www.wowwiki.com/Runner)) is on low HP he attempts to run away in fear. Thats a normal behavior.

**Bug.**
If after the ["fear"](http://www.wowwiki.com/Runner) caster mob have no mana he will stay at one place and do nothing until he have mana for a cast, he will only attack(melee) if player is in melee range. After the cast he is back to normal behavior.

Tested on [Bonechewer Evoker](http://www.wowhead.com/npc=19701/bonechewer-evoker),  screenshot - [img](http://i.imgur.com/r8QBzdR.jpg?1).

**Comment by Bearmanpig** [comment] 2015-01-18 16:58
This happened to my party as well in the Hellfire Ramparts instance yesterday, but it happened to melee mobs. They stopped attacking completely, even when you moved into melee range. There was no way to 'un-bug' them.

**Comment by ccshiro** [comment] 2015-01-18 17:05
Duplicate of #91 and #131.

But this is a really good analysis so I'm keeping this one open.

**Closed as completed** 2015-03-03 21:14 UTC
Labels: bug
