### ISSUE TITLE
Macro issue ?

### ISSUE THREAD

**Issue by Dailybs** [ccshiro/cc-buglist#128] opened 2015-01-18 05:18 UTC
Again no pics just let me tell you something I found, while killing stuff with my BM Hunter I use this macro
# showtooltip Steady Shot

/script UIErrorsFrame:Hide()
/castsequence reset=# Steady Shot, !Auto Shot
/cast [exists,target=pettarget] Kill Command
/script UIErrorsFrame:Clear(); UIErrorsFrame:Show()
And when I kill few mobs with this macro, then on the next mob I can't use the macro, what I mean - my hunter won't shoot with the macro, I need to manually pull my melee weapon by casting melee spell or manually pull ranged by casting ranged skill (without macro) and then my hunter can use this macro again thx.

**Comment by Dailybs** [comment] 2015-01-18 06:34
Okay the problem is in the macro, Glory to God.I just found the issue and the solution here is the reworked macro - 
#showtooltip Steady Shot
!Startattack
/castsequence !Autoshot, Steady Shot

Needless to say I had to put command for starting auto attack to fix this problem of mine, I hope other hunters will use the correct macro.Also don't go and think you lose 1st Steady shot because there is !autoattack, because in reality what it does is drows the bow, while I pump the jam, wait the button and it instantly begins Steady shottin :D

**Comment by Iliana-sc** [comment] 2015-01-18 10:47
If this is not a bug you should close the issue

**Comment by vauhs** [comment] 2015-01-19 19:23
I used the exact macro originally posted and had no issues whatsoever, the only issue I see is you didn't change the "#" to your attack speed +1ms. Maybe that was the issue?

**Comment by ccshiro** [comment] 2015-02-05 02:25
I'll close this if no issue seems to exist?

**Closed as completed by ccshiro** 2015-02-05 02:25 UTC
Labels: invalid
