### ISSUE TITLE
Pvp Issues

### ISSUE THREAD

**Issue by Bugreporta** [ccshiro/cc-buglist#592] opened 2015-06-05 17:25 UTC
Had a duel vs a rogue (I'm a priest)

1 @ If he opens with sap into cheap/kidneyshot (while i'm still sapped). The sap will last basicly until i relog.

2 @ Another bug is i am unable to use pvp trinket on cheap/kidneyshot and blind. Have not tested with any other stun/cc.

3 @ As of current state, if you are blinded (in a duel) you can use any instant cast while sitting in the duration of the blind.

**Comment by Stoney21** [comment] 2015-06-05 17:38
https://github.com/ccshiro/cc-buglist/issues/584

**Comment by LikeVenom** [comment] 2015-06-05 18:36
confirming. tested with druid's bash and couldn't trinket. cyclone as well.

**Comment by ceyscro** [comment] 2015-06-05 18:40
Then about trinket, I did not test every stuns but there are some you can trinket and others you can't.
You can't trinket sap,cheapshot,kidney shot, gouge

What I could trinket : fear, mind control, deathcoil, blind.

**Comment by ccshiro** [comment] 2015-06-06 15:36
1 and 3 should have been fixed already. 2 is bugged, but duplicate of #584.

**Closed as completed** 2015-06-06 15:37 UTC
Labels: duplicate
