### ISSUE TITLE
Logging Out While In Combat Shouldn't Be Possible

### ISSUE THREAD

**Issue by YourNewfriend** [ccshiro/cc-buglist#943] opened 2015-07-06 01:07 UTC
A character shouldn't be able to disappear from the gameworld, and deaggro monsters by logging out, because combat should prevent the character from disappearing.

If I initiate the logout timer before engaging a monster, I can successfully escape it by vanishing from the gameworld.

![image](https://cloud.githubusercontent.com/assets/13057166/8514284/6fa816a0-2340-11e5-9394-cc5cbac2c7e2.png)

When I logged back in, I was out of combat and had the same health I logged out with.

**Comment by PatchnotesTBC** [comment] 2015-07-06 08:25
Nasty bug

**Comment by Peonstomperx** [comment] 2015-07-06 10:15
you sure? https://youtu.be/icWqS9af6uc?t=1614

**Comment by ghost** [comment] 2015-07-06 10:23
"bug"

**Comment by YourNewfriend** [comment] 2015-07-06 10:23
You can't say that his character disappeared from the game world, even though he did reach the character selection screen, because he could've just died later.

You did solve one part of the puzzle.

**Comment by YourNewfriend** [comment] 2015-07-06 10:26
Maybe somebody with a retail account can try something similar to see what happens on panda wow?

We'll probably never figure this one out tbh

**Comment by ccshiro** [comment] 2015-07-06 15:07
This is the intended behavior. If you pass the 20 second log out timer without dying you are safe and removed from the world. Once initiated being put in combat does not break it. I will close this as invalid. If you want to reopen this you need to provide evidence for your claim.

**Closed as completed by ccshiro** 2015-07-06 15:07 UTC
Labels: invalid
