### ISSUE TITLE
[AH] Buyout instead of bid

### ISSUE THREAD

**Issue by Gehenas** [ccshiro/cc-buglist#230] opened 2015-01-18 20:34 UTC
There was 1 item in the auction house. It had a buyout price on it, both "bid" and "buyout" buttons were active. I clicked on "bid", but I got the message that I had won an auction. Got the item in mailbox. Bought the item in Orgrimmar.

note: it is possible that the auction lasted for 12 hours and I placed my bid at 11h 59m 59sec so I immediately won, but it's very unlikely.

**Comment by FurioCC** [comment] 2015-01-18 20:39
Just provide info what you bought so devs do not have to build theories and just check logs.

**Comment by Gehenas** [comment] 2015-01-18 20:45
Unfortunately something interrupted me and by the time I got back to wow I forgot to write the issue... it was this afternoon, the icon of the item was red-ish, the price was 400something gold. My test acc: TEST2420. The character was either Gehenas or Gehenass. That's all I remember.

**Comment by arawnik** [comment] 2015-01-18 22:37
Are you sure the bid price was way lower than the BO price? because if your new bid reaches BO price that's what's supposed to happen. Might be one cause for the problem and I didn't see you specify the item bid/BO price.

**Comment by Gehenas** [comment] 2015-01-18 22:55
I didn't change any values, just searched and clicked bid. Also, there was no confirmation window like when you buyout something.

**Comment by TylkaCC** [comment] 2015-01-19 03:36
There's not supposed to be a confirmation window when you bid a amount equal to the buyout price.

**Comment by ccshiro** [comment] 2015-02-05 01:23
Tested in-game, bid seems to work correctly. Namely:
- Bid does not give a confirmation window (it shouldn't, and that's client-side anyway).
- If bid amount equals buyout you get the same outcome as with buyout (i.e., no wait time).
- If bid amount is less than buyout you place a bid and the item stays in the AH, allowing other people to bid as well.

All of the above described is how it's intended to work, so I'm closing this as not a bug.

**Closed as completed by ccshiro** 2015-02-05 01:23 UTC
Labels: invalid
