### ISSUE TITLE
Mana restoring gem is wrong.

### ISSUE THREAD

**Issue by ghost** [ccshiro/cc-buglist#1214] opened 2015-08-09 20:17 UTC
Mana procc triggered by "sitting to drink" -- /using water item

1.create a mana-using class, get to vll70, get a helmet which can hold a meta
2.buy the http://www.wowhead.com/item=25901/insightful-earthstorm-diamond 
3. spam /use water item
4. at some point it will proc regenerating 300 mana

proof: the sole tooltip states it proccs from "Spells"

![manarestore1](https://cloud.githubusercontent.com/assets/13721369/9156713/0f3a1cb8-3ee4-11e5-9c85-12c5d745e289.png)
![manarestore2](https://cloud.githubusercontent.com/assets/13721369/9156714/0f3cbf7c-3ee4-11e5-80bf-4a630177ebe8.png)

**Comment by ConfusedCC** [comment] 2015-08-09 21:06
duplicate of  #993

**Closed as completed** 2015-08-09 21:23 UTC
