### ISSUE TITLE
[Slave pens] - The patrol in picture,

### ISSUE THREAD

**Issue by KMKM2696** [ccshiro/cc-buglist#2115] opened 2015-12-16 23:59 UTC
![lolbug](https://cloud.githubusercontent.com/assets/16328326/11857434/1bd135c0-a450-11e5-8a80-38a4396b4b21.jpg)

Once the patrol has been pulled and there has been a wipe from the patrol said patrol will just remain in place and will no longer continue to move until pulled. Thanks.

**Comment by ccshiro** [comment] 2016-01-25 21:53
Noticed this issue is a duplicate of #1220.

**Closed as completed by ccshiro** 2016-01-25 21:53 UTC
Labels: bug, duplicate
