### ISSUE TITLE
Feralfen village, minor bugs with mobs in Zangarmarsh

### ISSUE THREAD

**Issue by nullfoxh** [ccshiro/cc-buglist#695] opened 2015-06-07 12:01 UTC
The hunter:
http://www.wowhead.com/npc=18113/feralfen-hunter
and his pet:
http://www.wowhead.com/npc=18201/tamed-sporebat
and the druid:
http://www.wowhead.com/npc=20270/feralfen-druid

I found a few issues in this area:
1. If I sap the hunter and kill the pet, the hunter will instantly resummon a new sporebat once sap is broken. This bug happened to me 3/5 times. He will not resummon the sporebat if the sporebat is killed while the hunter is not sapped.
2. If you move into the hunters deadzone (it can't attack with ranged nor melee) he will stand there doing nothing for a long while. He might trap you and throw in a serpent string, then wander around again, until he maybe moves out of the deadzone and starts attacking you.
3. If you normally pull (bodypull, ranged) the druid he will change into bear form and attack you, if you however sap or stun him first, he will not change into bear. Not sure if intended or not.
4. Upon further investigation it would seem the druids should shapeshift into owls and not bears: as can be seen here: https://youtu.be/hAoN2OH2Fn0?t=236 and here: http://www.wowhead.com/npc=20270/feralfen-druid#comments

Video showing the summon issue (8,5mb):
http://webm.host/66d07/
Sadly webm does not accept my videos of the pathing issues. I tried 3 different videos.

**Comment by nullfoxh** [comment] 2015-06-07 12:22
After further testing I have come to the conclusion that issues 1. and 2. are most likely not bugs with the mobs but rather Sap, as neither of these issues happen without sap and Sap causes all sorts of erratic behavior in mobs. I will post more details in my Sap report here: https://github.com/ccshiro/cc-buglist/issues/671

**Comment by ccshiro** [comment] 2015-06-17 18:10
In the future, please make one issue on the tracker per bug you report. Multiple bugs per issue makes it really annoying to manage the tracker. Thanks.

As for the bugs:
1. This was related to sap. Should've been fixed in another issue already.
2. This was related to sap. Should've been fixed in another issue already.
3. Nim tried it on retail with the same outcome. Not a bug.
4. Was indeed bugged. Fixed now.

**Closed as completed by ccshiro** 2015-06-17 18:10 UTC
