### ISSUE TITLE
Spell Delay / Stopcasting

### ISSUE THREAD

**Issue by Peonstomperx** [ccshiro/cc-buglist#1414] opened 2015-08-17 14:12 UTC
https://youtu.be/ScAImPXZQOc?t=644 Spam swd while casting to break cc.
https://youtu.be/ScAImPXZQOc?t=679 Spam rocket while casting to break vanish.

It seems like stopcasting should happen earlier than spell apply.
http://www.arenajunkies.com/topic/113579-swd-trick-from-hydra7/

**Comment by nullv0id** [comment] 2015-08-17 14:31
That's from WOTKL. Not TBC.

**Comment by Peonstomperx** [comment] 2015-08-17 14:37
@nullv0id I don't think there were any major mechanic changes from 2.4.3 to wotlk, but I'm looking for it in tbc videos atm.

**Comment by nullv0id** [comment] 2015-08-17 14:50
I wouldn't consider it a major mechanics change, rather they were trying to improve the netcode. It was never documented in the changelogs either. I'm pretty sure you won't find this in TBC videos, but good luck :) Try asking on IRC too, because I remember discussing this with someone.

**Comment by SuddenDeath** [comment] 2015-08-17 21:56
@Peonstomperx Those videos are from the short time in wotlk when blizzard made some change to their spell batch system which caused this major fuck up. It got fixed 1-2 months later. It was not intentional. I remember it very clearly, there were some threads on mmowned explaining it back then.

This was also around the same time Blizzard messed up DKs death grip, about 50% of the time it wouldn't cancel your spell cast until you landed, or sometimes it didn't cancel it at all. 

They made some changes which caused strange things happened during a few times in wotlk.

**Comment by Schaka** [comment] 2015-08-19 16:05
I can confirm what @SuddenDeath said. Would be great if we could find the threads on ownedcore now, because I remember specifically people abusing the shit out of this, when it popped up mid-wotlk.

**Comment by justinbeaver** [comment] 2015-08-23 22:31
Basically here are two different reports:

<b>First</b> is about to break CC with swd and I pretty sure it's only wotlk thing.

But <b>second</b> is about buffering ability to break vanish. As we're know if you hit rogue in window between he uses vanish (we can see him with vanish buff) and when he is completely invisible it will break vanish. For example druid is casting starfire and spamming moonfire at that time, if rogue goes vanish, starfire cast stops but due to moofire spam it will break his vanish.
Screen from CC:
![3](https://cloud.githubusercontent.com/assets/13700367/9430342/589d5042-49a6-11e5-9e3d-5c087e6635db.jpg)
There are many topic from different wow expansions that especially hunters are breaking vanish. Why it's happens? Because of this "buffering". Every hunter is spamming arcane shot button like mad while casting aimed shot, to shoot as fast as possible after aimed, but when rogue is going vanish, aimed cast stops and acrane shot goes instantly in this vanish window and break him.

Some screenshots as always:

Hunter is casting aimed shot
![untitled](http://i.imgur.com/ct3VmwX.jpg)
Rogue is using vanish, aimed shot cast is stopped
![untitled](http://i.imgur.com/e6vxYRF.jpg)
But hunter is still smashing aimed shot button so he is starting second aimed shot in this vanish window. If it was arcane shot, then vanish would break.
![untitled](http://i.imgur.com/oCqY4wp.jpg)
Then rogue is invisible, but aimed cast didn't stopped.
![untitled](http://i.imgur.com/ztCwDyp.jpg)
And druid got him with warstomp.
![untitled](http://i.imgur.com/fpKZ1Go.jpg)
Aimed goes off
![untitled](http://i.imgur.com/RfBMNXJ.jpg)
https://youtu.be/9qv4nbt-NNk?t=831 set speed to 0.25 here

**Comment by nullv0id** [comment] 2015-08-23 22:41
Could you provide a link to a thread that says you should be able to break vanish by spamming an instant while casting. Only thing I was able to find was the ones about hydras video, which became a thing in wotlk and was later fixed.

**Comment by justinbeaver** [comment] 2015-08-24 09:16
@nullv0id
I'm looking for some info with spell instant.
But would be nice to see why it should not be possible, if your cast is stopped, rogue with vanish buff is in your target and you spamming any instant spell, what kind of error it tells you or something? If someone has any info on this this is the right topic to post.

**Comment by Peonstomperx** [comment] 2015-09-03 03:46
stopcasting happens before CC applies, question is if server allows casts in that time

https://youtu.be/MwpircSE2hI?t=45 hydra 3(s2?) kidney shot while casting
https://youtu.be/QyTyNaiEJKs?t=229 s4 cyclone while casting
https://youtu.be/Fv_CJDCmGO8?t=73 s4 charge while casting

**Comment by ccshiro** [comment] 2015-09-25 20:31
I don't see any proof in here that in TBC you could get a cast off in between the interrupt and the CC application. I will close this as invalid, if anyone finds something please post it in here and PM me on irc and I can reopen it.

**Closed by ccshiro** 2015-09-25 20:31 UTC
