### ISSUE TITLE
Invisible Infernal

### ISSUE THREAD

**Issue by ebonywolf** [ccshiro/cc-buglist#979] opened 2015-07-06 17:44 UTC
Problem: Summoned a infernal and it had no meshes, My friend couldnt see or click the infernal either.

Reproduce: I had summoned many infernals before and after the event but all worked fine except this case. (I also hadnt done anything in particular).

proof: http://postimg.org/image/5l5cw6xm5/

**Comment by Mephisto22** [comment] 2015-07-06 19:58
I summoned an infernal once and couldnt see him either. I consider it minor bug since infernal is basically useless pet

**Comment by darkcranio** [comment] 2015-07-06 23:02
#588

**Comment by ccshiro** [comment] 2015-07-16 21:04
I poked at it in #588 without really being sure why the bug happened (it's strange, the model is set correctly, etc), but it stopped becoming invisible for me so I thought I had found it. Apparently not. Since I still don't see what's wrong, I did some changes that might have effect. Then again they might not. Would like an update if you guys see it again next test.

**Comment by ccshiro** [comment] 2015-07-23 23:13
Nervermind, I got it to happen again.

**Comment by demerda22** [comment] 2015-07-27 11:32
pwned! hAhA

**Comment by ccnim** [comment] 2015-07-28 01:22
I can no longer reproduce this after the new fix we implemented so I'm going to close this in hope that it's actually gone this time.

**Closed as completed by ccnim** 2015-07-28 01:22 UTC
Labels: bug
