### ISSUE TITLE
no preparation before arena starts

### ISSUE THREAD

**Issue by Isuel** [ccshiro/cc-buglist#441] opened 2015-04-20 21:21 UTC
title is self explanatory, before the arena starts, there is no preparation buff, the one which makes ur spells instant and which heals u and gives u mana.

**Comment by Chulain** [comment] 2015-04-20 21:34
duplicate of https://github.com/ccshiro/cc-buglist/issues/430

**Closed as completed** 2015-04-21 14:47 UTC
Labels: duplicate
