### ISSUE TITLE
Dreghood Brutes are sometimes stuck in place and not meleeing you

### ISSUE THREAD

**Issue by netherspite** [ccshiro/cc-buglist#205] opened 2015-01-18 17:22 UTC
Dreghood Brutes in the Ruins of Sha'naar are sometimes stuck in place after they have freeze debuff (from frost nova) removed and they try to reach you. They stay close to you but not melee you. They can, however, use Hamstring on you.
Attaching screenshots of two places I noticed this happening.

**Comment by netherspite** [comment] 2015-01-18 17:22
![wowscrnshot_011815_183100](https://cloud.githubusercontent.com/assets/5777848/5793300/4a7d4be8-9f47-11e4-9e0a-69832e3c0090.jpg)
![wowscrnshot_011815_183643](https://cloud.githubusercontent.com/assets/5777848/5793302/50a574e6-9f47-11e4-98a4-6f72dbb119a5.jpg)

**Comment by ccshiro** [comment] 2015-01-18 19:53
Probably duplicate of #190 (and if not they're not reference in that thread and I can check them easily together).

**Closed as completed by ccshiro** 2015-01-18 19:53 UTC
Labels: duplicate
