### ISSUE TITLE
Corruption with 5/5 Improved Corruption Talent doesnt cast instantly

### ISSUE THREAD

**Issue by PantelisK** [ccshiro/cc-buglist#1127] opened 2015-08-08 12:55 UTC
With 5/5 Improved Corruption talented and my back turned on a mob i couldnt instant cast Corruption. As shown in the printscreen i am getting the error message "cant do that while moving"
![untitled](https://cloud.githubusercontent.com/assets/5631772/9150521/af0ee3c2-3de5-11e5-8828-3a974b8e56bb.jpg)

**Comment by Klimpb** [comment] 2015-08-08 15:27
Have had this happen to me before, the spell is still instant but you have to stand still to cast it. Quite a rare bug.

**Comment by Ickler** [comment] 2015-08-08 23:14
Hmm I've seen this on other Pservers, and often that also means that tanks when using instant abilities (spells) such as holy shield or other abilities counts as "casting" and removes all chances to block, dodge or parry. Great way to make sure you wipe on bosses when you think you're uncrushable.
Worth checking out for sure.

**Comment by Pinhastest** [comment] 2015-08-11 22:50
Related #941 for sure. We just need reproduction steps, but looks like its random

**Comment by ccshiro** [comment] 2015-08-21 16:39
@Pinhastest you're right, this looks it has the same cause as #941. I will move #941 into Needs Testing, and close this one as a duplicate.

**Closed as completed by ccshiro** 2015-08-21 16:39 UTC
Labels: duplicate
