### ISSUE TITLE
Yellow quest ?'s remain after turning in quests

### ISSUE THREAD

**Issue by ghost** [ccshiro/cc-buglist#591] opened 2015-06-05 17:02 UTC
Continued quests in netherstorm that I had picked up during last test. Turning them in did not remove them (though they disappear if you relog).

**Comment by rylaiii** [comment] 2015-06-05 17:30
duplicate - #524

**Comment by ccshiro** [comment] 2015-06-06 15:38
Duplicate of #524. Please post instructions how you achieved the bug there.

**Closed as completed by ccshiro** 2015-06-06 15:38 UTC
Labels: duplicate
