### ISSUE TITLE
[Quest] When the Cow Comes Home - Bessy - Attacking Mobs and Player

### ISSUE THREAD

**Issue by moshamaniac** [ccshiro/cc-buglist#1590] opened 2015-09-02 12:43 UTC
Quest ID: 10337
http://www.wowhead.com/quest=10337/when-the-cows-come-home

When i was doing this escort quest, Bessy attacked mobs, which judging from several wowhead comments, she should not, for example user Dennace:
"Something went weird with this quest, I found that if I aggroed she just kept walking... Which.... didnt matter because I could just stay back and kill them, didnt need to worry about how far away I was..."
https://youtu.be/1La1AhcD_0o

 Also, after killing one mob, she suddenly decided to drop the hammer on me, her remote relative. She does good damage too, as you can see in this video:
https://youtu.be/G0-lruOa9so

I was able to reset her from attacking me by running away, then she continued to go down her path, mauling all the mobs in her way. seriously, what did she need me for?

This quest can easily be completed as it is though.

**Comment by netherspite** [comment] 2015-09-02 13:56
Hmm seems this was not really fixed: #1505 
Also nice observation that she should not attack mobs at all.

**Comment by ccshiro** [comment] 2015-09-03 18:07
Duplicate of #1505, also the fix wasn't in yesterday when you tried it. Would be nice if you could try it again, please.

**Closed as completed by ccshiro** 2015-09-03 18:07 UTC
Labels: duplicate
