### ISSUE TITLE
[Spell] Ritual of Summoning

### ISSUE THREAD

**Issue by ghost** [ccshiro/cc-buglist#1565] opened 2015-08-31 15:21 UTC
we could not click the summoning portal unless we relogged

steps to reproduce:
1. have a lock in party
2. get to mid instance (not sure if relevant)
3. wipe meni times so there is a need to repair
4.let the tank (Druu) HS out for repair
5. try to resummon him inside
6.portal will not be clickable
7. OPTIONALLY log out and log back in for the portal to be clickable (clickers are the ones who gotta relog -- not tested with warlock relog)
8.rant on the IRC and ask nim for help
9. have nim show up
10.profit

PD1: most likely non related but this happened in the same instance as #1563 
PD2: Nim ported to us and "saw" it happen 
PD3: Read Lynxzor comment below, apparently he had it happen too on dungeon summoning stones

![captura de pantalla 2015-08-30 a las 17 01 10](https://cloud.githubusercontent.com/assets/13721369/9582186/0f1b15e4-5004-11e5-8e51-4c930ecba9f7.png)
![captura de pantalla 2015-08-30 a las 17 00 02](https://cloud.githubusercontent.com/assets/13721369/9582187/0f1ff67c-5004-11e5-9b32-d2fc42de6e76.png)

**Comment by lynxzor** [comment] 2015-09-01 10:47
Happens with normal summoning stones also (not sure how to reproduce yet)

**Comment by ghost** [comment] 2015-09-01 10:48
@lynxzor  what ive seen with summoning stones is that although you click them, they do not "trigger" the summon. this however prevented us from clicking it all together

**Comment by lynxzor** [comment] 2015-09-01 10:52
It's happened a couple times where you can't click altogether until relogged, just like this issue.

**Comment by ghost** [comment] 2015-09-01 10:54
@lynxzor ill edit my issue to that devs notice your issue, dindt happen to me though, guess i was just lucky

**Comment by lynxzor** [comment] 2015-09-01 10:58
If you notice this again with the lock summon then go out and see if it also occurs with the summoning stone (pretty sure it should be the same)

**Comment by ccshiro** [comment] 2015-09-22 17:52
Duplicate of #899 and #509.

**Closed as completed by ccshiro** 2015-09-22 17:52 UTC
Labels: duplicate
