### ISSUE TITLE
Mobs despawn (visually) upon death

### ISSUE THREAD

**Issue by nz54445** [ccshiro/cc-buglist#68] opened 2015-01-17 21:15 UTC
After dying in OHF HC by a group of mobs they visually despawned. I could not see them on the screen and they had the run/fade animation that rogues usually have when stealthing or mobs have when despawning. However, the rest of my group could evidently see the mobs and were fighting them. From time to time the mobs would appear (only when they started their run away animation at low health). Difficult to reproduce and it only happened on one of our many wipes. Have a couple of screenies that did not catch everything but you can see they are fighting some invisible mobs:

http://pbrd.co/1wiMiot http://pbrd.co/1wiMlAN

**Comment by ccshiro** [comment] 2015-02-06 15:02
This is an issue I had happen to me as well. But now I can't reproduce it. It's possible it got fixed as part of another change, I suppose. Before it happened to me a lot (I thought it was every time), now I've tried some 20 times without getting it. I'll close it for now. If it happens again, please reopen this.

**Closed as completed by ccshiro** 2015-02-06 15:02 UTC
Labels: bug
