### ISSUE TITLE
Difficulty in casting spells when targets are circling around you.

### ISSUE THREAD

**Issue by Klimpb** [ccshiro/cc-buglist#154] opened 2015-01-18 11:59 UTC
Spells that require you to be facing the enemy when casted are very difficult to cast when targets are circling around you (even more if they have increased movement speed). Can take up to 3 seconds for you just to start casting a spell, not how I remember it from retail.

Had around 45 latency when recording this(though it might not seem like it judging from the ActionBars, but that's what the game said)

![buglow](https://cloud.githubusercontent.com/assets/9938017/5792284/58212372-9f11-11e4-9d1a-23a77a68c48e.gif)

Full video: https://mega.co.nz/#!nUU0CDIC!OpLy0rF3HyjcDAlX-odBiXc4SOh8XRfIN3W6ItewYxg

**Comment by ccshiro** [comment] 2015-02-05 02:16
I think this was probably caused by the server lag we had. Going to close it, please feel free to repon if it persists next test.

**Closed as completed by ccshiro** 2015-02-05 02:16 UTC
Labels: invalid
