### ISSUE TITLE
Spamming Nature's swiftness bug

### ISSUE THREAD

**Issue by Ickler** [ccshiro/cc-buglist#234] opened 2015-01-18 22:40 UTC
Spamming Nature's swiftness, then really quickly spamming a cast ability makes the Nature's swiftness disappear and gives no instant cast. 

I would assume this might also be the case for other instant abilities (presence of mind), also might have an effect on things such as elemental mastery. But never got to test these.

**Comment by Iliana-sc** [comment] 2015-01-19 04:10
likely a duplicate of #106

**Comment by FurioCC** [comment] 2015-01-19 10:17
Might be that abilities that is not triggering GCD, are still waiting in update queue for server confirmation when you queue cast of the next spell, which results in server treating those casts as normal and then consuming buff retrospectivly.

**Closed as completed** 2015-01-20 15:21 UTC
Labels: duplicate
