### ISSUE TITLE
[Missing NPC] Yuula, Sha' tari skyguard Recruitment Officer and Skyguard Nether Ray

### ISSUE THREAD

**Issue by mara1987** [ccshiro/cc-buglist#304] opened 2015-03-31 22:22 UTC
I've noticed the missing NPCs when unlocking the flight path in Shattrath. They are supposed to be near the flight path guy but they were absent. Also after server restart i didn't find them. Yuula is the one questgiver that unlocks daily quest in sketties.

Thanks

**Comment by nz54445** [comment] 2015-03-31 22:32
This should be working as intended: http://www.wowwiki.com/Patch_2.1.0, Skyguard was introduced in content patch 2.1, whereas the server is running 2.0.3. Would need confirmation on this, but I'm 99% sure they should not be there.

**Comment by mara1987** [comment] 2015-03-31 22:34
So they will be introduced later on or are you planning not to?

**Comment by nz54445** [comment] 2015-03-31 22:38
Corecraft will introduce these quests and more as time goes by in incremental patches. 

From the F.A.Q

Q11 Content -- What patch is the content? Will keys be revered, will drops be 2.0.3, etc?
The content will be 2.0.3 with a few variations made out of necessity -- for example, things that were impossible (Morogrim's first version), or that made no sense (Karazhan gear being terrible in comparison to its level) will not be brought back.
Here are some key points that are generally brought up for questioning:
1. Keys & Attunements -- Will be 2.0.3. All attunements will be in-game and required. Heroic keys will require revered.
2. Badge of Justice -- Will only drop in heroics, and not in raids.
3. Loot -- Items that were not available in 2.0.3 will as a general rule not drop until we reach the content patch they started dropping in.
4. Boss Mechanics -- Mechanics will be as they were in 2.0.3. Some exceptions do exist. Some examples; Kael'thas will of course not have his bugs reintroduced, as he was heavily bugged in 2.0.3, Morogrim will not have the unkillable Water Elemental adds that he had for a very, very short time.

**Comment by mara1987** [comment] 2015-04-01 09:10
Thanks a lot. I did read the F.A.Q. but i missed the "Loot" part.

**Closed as completed** 2015-04-01 11:15 UTC
Labels: invalid
