### ISSUE TITLE
Item still glowing after being picked up

### ISSUE THREAD

**Issue by PatchnotesTBC** [ccshiro/cc-buglist#1186] opened 2015-08-09 05:51 UTC
Screens:
http://i.imgur.com/2vrOzHw.jpg
http://i.imgur.com/dpn6KDj.jpg

Several off these keep glowing after pick up should Disapear as soon as i picked it up but it did not.

The quest is  [I Work... For the Horde!]

**Comment by ConfusedCC** [comment] 2015-08-09 08:42
duplicate of #434

**Closed as completed** 2015-08-09 10:08 UTC
Labels: duplicate
