### ISSUE TITLE
Another movement bugg

### ISSUE THREAD

**Issue by ghost** [ccshiro/cc-buglist#1408] opened 2015-08-16 23:44 UTC
Mob is accidentally jumping.
![wowscrnshot_081715_084214](https://cloud.githubusercontent.com/assets/13764565/9295747/24d90114-44bc-11e5-9e4f-0a125e36c1f9.jpg)

**Comment by ASrozaev** [comment] 2015-08-18 07:33
I see plainstrider staying one leg

**Comment by ccshiro** [comment] 2015-09-25 21:02
Duplicate of #1225.

**Closed as completed by ccshiro** 2015-09-25 21:02 UTC
Labels: duplicate
