### ISSUE TITLE
(UI) Nameplates casting

### ISSUE THREAD

**Issue by Bzmode** [ccshiro/cc-buglist#1098] opened 2015-08-08 02:58 UTC
the nameplate castbar seems to be completely broken you can see the spell they are casting but not the progress of it.

**Comment by Jigodian** [comment] 2015-08-08 03:22
Happened to me. After that I clean installed TBC again and it worked fine again. It's a client side problem for sure.

**Comment by Bzmode** [comment] 2015-08-08 03:29
ok i'll leave this open for now let shiro decide what to do with that information might help other people having the same problem I am

**Comment by Schaka** [comment] 2015-08-08 06:45
This was a common bug during retail, where the castbar on nameplates would sometimes just break. There is even an addon around that can fix this.

**Comment by nullfoxh** [comment] 2015-08-08 11:28
Duplicate of your other report? https://github.com/ccshiro/cc-buglist/issues/686

**Closed as completed** 2015-08-08 15:00 UTC
Labels: duplicate
