### ISSUE TITLE
[Mage] Arcane Potency talent with Arcane Missiles

### ISSUE THREAD

**Issue by punker85** [ccshiro/cc-buglist#523] opened 2015-04-21 16:07 UTC
This talent should apply a static +30% chance to critical chance on top of what the mage already has for critical spell strike chance to any spell that is casted with the Clearcasting buff from Arcane Concentration.  After several repeated barrages of Clearcasted missiles tested on target dummies, the result critical chance shown in Recount was 30% when my mage character had 22% spell critical strike chance in the character portrait.  The results should show some 50%+ critical projectiles landing.  Also as stated in http://www.wowwiki.com/Arcane_Potency, the Arcane Potency critical buff should be applying to any spells currently being casted while receiving the Clearcasting buff.  

This bug https://github.com/ccshiro/cc-buglist/issues/520 is also interfering with these interactions.  It makes the use of Lightning Capacitor on an Arcane mage almost worthless because I should be able to get a very high amount of criticals from chain casting Arcane Missiles if a Clearcasting buff was given during channeling them.  The buff also should not be consumed until the start of a new spell casted is finished (or canceled if its a channeled spell).

**Comment by ccshiro** [comment] 2015-04-22 20:18
I'm assuming that arcane potency should apply for all ticks of arcane missiles, but that it doesn't since clearcasting disappeared already. Maybe the ticks should use the talent's increased crit if if was active when the channel started? And if so, does that apply just for Arcane Potency or for other crit auras? And if so, for other spell modifiers as well? Like a spell power increase, for example?

Could use some research into what exactly is going on.

**Comment by Philosophers** [comment] 2015-04-23 09:13
http://wow.gamepedia.com/Arcane_Potency?cookieSetup=true

"This talent has somewhat peculiar synergy with Arcane Missiles, and a mage who uses  [Arcane Missiles] as part of his rotation"

There is a note that this quote applies to cataclysm, BUT in patch notes there have clear information, that this patch did not change the nature of talent. I guess that on corecraft arcane potency applies only to the first arcane missle and the others have default crit chance, where it should apply to all channeling ticks.

Also:
http://wow.gamepedia.com/Arcane_Missiles

There is clear patch notes, so nature of spell was not touched too. Here stands:
"While you stand and channel, Arcane Missiles launches bolts of arcane energy at your target, dealing the given damage each second. Unlike other channeled spells, each second (or "tick") is considered a separate direct damage missile which passes through the normal direct damage checks (crit, resistance)."

So arcane missles should behave exaclty the same as fireball or frostbolt, when it comes to other crit auras, spell modifiers etc. missles should use them all (except for presence of mind).

"A notable effect of the fact is that "on spell hit" abilities, such as  [Mark of Defiance](http://wow.gamepedia.com/Mark_of_Defiance), can proc off each missile, similar to "on spell crit" abilities. However, "on spell cast" abilities, such as  [Mystical Skyfire Diamond](http://wow.gamepedia.com/Mystical_Skyfire_Diamond), only have a chance to proc on each casting of the spell, not on each bolt."

"Furthermore, both the initial cast of Arcane Missiles and each Missile are considered spell hits, resulting in a maximum amount of 6 hits per cast."

I think this is clear, isn't it?

**Comment by punker85** [comment] 2015-04-24 00:36
Check history of Arcane Potency [http://www.wowwiki.com/Arcane_Potency?action=history] and read the entries for Jan 30, 2008 [http://www.wowwiki.com/Arcane_Potency?oldid=1160300] and March 12, 2008 [http://www.wowwiki.com/Arcane_Potency?oldid=1256773].  They clearly state different functionality but it is long before the WOTLK patch.  The FIRST says "Updated with new information (Arcane Missiles Synergy)" where it makes erroneous claims about Clearcasting.  The SECOND says "Removed some incorrect information about the function of Arcane Potency" which promotes that while the buff is active all channeling projectiles from spells should have an additional 30% chance to critically strike and any spell that consumes the buff should also critically strike with 30% increased chance.  The lack of this functionality hampers the arcane specialization by a decent amount.  With a near perfect rotation of missiles on Clearcasting, I was getting 10% damage less than what I shouldve been getting.  Then again, I didn't even bother to test if the spellpower coefficient was correct for each missile hit.

**Comment by Soda-88** [comment] 2015-04-24 11:57
Clearcasting buff gets consumed on spellcast, not on channel finish. With that said, crit chance should be calculated at the start of channeling, so that entire channeling of Missiles get the boosted crit chance and not just the first missile. This prevents the abuse of getting two full missiles with bonus crit and for free if you time your recast right (just before the first one finished), or any other spell cast on the back of Missiles for that matter.

https://www.youtube.com/watch?v=6CkYaF8EKb0&t=7m28s

Pay close attention to buffs, when the mage recasts Arcane Missiles

**Comment by ghost** [comment] 2015-05-21 21:56
I think that what you guys are describing is known as snapshotting.
I was aware of its extended use in pvp before it got nerfed around the start of the current retail expansion.
Here's a thread on the official WoW forums that's relevant:
http://us.battle.net/wow/en/forum/topic/9377319811

Snapshotting extends to every dot/hot in the game.
Basically, the damage and healing done is calculated once at the beginning of a spell based on the stats you have then.

**Comment by ccshiro** [comment] 2015-05-22 16:57
@SorcerersApprentice The implicit "snapshotting" effect for other DoTs does not naturally apply to Arcane Missiles since it's not a DoT, but actual individual spell casts for each missile.

**Comment by ccshiro** [comment] 2015-05-22 17:28
Reading the sources it seems to me the mechanic is that if clearcasting procs during the Arcane Missile channel, the following missiles will be affected by the crit, but the clearcasting will not be consumed. Since it's not consumed you can then go ahead and use it next cast as well.

Assuming I understood the mechanic, this is already working as intended (tried it just now). As such I'm removing the bug tag and closing as invalid.

**Closed as completed by ccshiro** 2015-05-22 17:28 UTC
Labels: invalid

**Comment by ghost** [comment] 2015-05-22 23:31
@ccshiro I'm sorry, must have been tired; I meant to point out that "snapshotting" in a sense extends to every ability in the game and reveals how damage/healing was calculated back then by the server. I don't know, however, how clearcasting works so I have no comments on that end.

**Comment by punker85** [comment] 2015-05-26 13:19
@ccshiro did you actually change anything about the mechanic in code before you tested this?  I was not getting this feeling of high crit chance when the talent would proc during mid cast of Arcane Missiles.  It is not only the Arcane Missiles that is currently being cast while the buff appears that receives the Arcane Potency buff but also the following cast of Arcane Missiles that will consume the buff that should get the 30% crit chance bonus.
