### ISSUE TITLE
[Mage] Clearcasting from Arcane Concentration talent

### ISSUE THREAD

**Issue by punker85** [ccshiro/cc-buglist#520] opened 2015-04-21 15:54 UTC
The Arcane talent Arcane Concentration can give a Clearcasting buff that should reduce the mana cost of my next spell cast.  However, the buff is disappearing at the end of my current spell cast if I receive the buff while casting (this did not happen during the case of a channeled spell like Arcane Missiles though).  Also, it was not reducing the mana cost of the current spell cast.  So I would receive the buff, get no benefit of the buff, and then lose the buff in some cases.  The buff should link to the start of the next spell cast and then disappear when that spell cast finishes.

**Comment by rylaiii** [comment] 2015-04-21 18:25
duplicate - #426

**Comment by punker85** [comment] 2015-04-21 19:27
https://github.com/ccshiro/cc-buglist/issues/426 references a different issue.  In #426, the chance to proc the Clearcasting state is referenced with respect to Arcane Missiles (which should be a 10% chance on each missile hit and NOT what is stated in Issue #426 which was changed after WOTLK).  This ticket (#520) is referencing how the buff should be applied to a spell being cast and when the buff should disappear.

**Comment by rylaiii** [comment] 2015-04-21 19:40
you are right. i shouldn't hop on github before drinking my coffee. i'll remove my comment.

**Comment by Chulain** [comment] 2015-04-21 23:27
duplicate of https://github.com/ccshiro/cc-buglist/issues/426

**Closed as completed** 2015-05-22 18:50 UTC
Labels: bug
